import Foundation
import SwiftUI

enum AppLanguage: String, Codable, CaseIterable {
    case japanese = "日本語"
    case english = "English"
    
    var identifier: String {
        switch self {
        case .japanese: return "ja"
        case .english: return "en"
        }
    }
}

class LocalizationManager: ObservableObject {
    static let shared = LocalizationManager()
    
    @Published var language: AppLanguage = .japanese
    
    private var translations: [String: [AppLanguage: String]] = [
        // Navigation / Tabs
        "Home": [.japanese: "ホーム", .english: "Home"],
        "Tide": [.japanese: "潮位", .english: "Tide"],
        "Rowing": [.japanese: "乗艇", .english: "Rowing"],
        "Practice": [.japanese: "練習", .english: "Practice"],
        "Settings": [.japanese: "設定", .english: "Settings"],
        
        // Home View
        "Good Morning": [.japanese: "おはようございます", .english: "Good Morning"],
        "Good Afternoon": [.japanese: "こんにちは", .english: "Good Afternoon"],
        "Good Evening": [.japanese: "こんばんは", .english: "Good Evening"],
        "Start Rowing": [.japanese: "Start", .english: "Start Rowing"],
        "Plan your session": [.japanese: "練習計画を立てる", .english: "Plan your session"],
        
        // Tide View
        "Tide Graph": [.japanese: "潮位グラフ", .english: "Tide Graph"],
        "High": [.japanese: "満潮", .english: "High"],
        "Low": [.japanese: "干潮", .english: "Low"],
        
        // MARK: - Settings View
        "Language": [.japanese: "言語", .english: "Language"],
        "Theme": [.japanese: "テーマ設定", .english: "Theme"],
        "Voice Feedback": [.japanese: "音声フィードバック", .english: "Voice Feedback"],
        "Sound Settings": [.japanese: "サウンド設定", .english: "Sound Settings"],
        "Sound Effects": [.japanese: "効果音", .english: "Sound Effects"],
        "Voice Guide": [.japanese: "音声ガイド", .english: "Voice Guide"],
        "Display": [.japanese: "表示設定", .english: "Display"],
        "Show Battery": [.japanese: "バッテリー状態を表示", .english: "Show Battery"],
        "Show GPS Accuracy": [.japanese: "GPS精度を表示", .english: "Show GPS Accuracy"],
        "Show Help Buttons": [.japanese: "ヘルプボタンを表示", .english: "Show Help Buttons"],
        "Weather Display": [.japanese: "天気予報を表示", .english: "Weather Display"],
        "非表示": [.japanese: "非表示", .english: "Hidden"],
        "アイコンのみ": [.japanese: "アイコンのみ", .english: "Icon Only"],
        "アイコン + 気温": [.japanese: "アイコン + 気温", .english: "Icon & Temp"],
        "アイコン + 気温 + 降水確率": [.japanese: "アイコン + 気温 + 降水確率", .english: "Icon, Temp & Rain %"],
        "フル表示": [.japanese: "フル表示", .english: "Full Display"],
        "Measurement": [.japanese: "計測設定", .english: "Measurement"],
        "Auto Start": [.japanese: "動作検出で自動開始", .english: "Auto Start"],
        "Units": [.japanese: "単位", .english: "Units"],
        "Distance": [.japanese: "距離", .english: "Distance"],
        "Speed": [.japanese: "速度", .english: "Speed"],
        "Data Sync": [.japanese: "データ同期", .english: "Data Sync"],
        "Coming Soon": [.japanese: "今後のアップデートで対応予定です", .english: "Coming soon in future updates"],
        "記録を自動でiCloudに同期": [.japanese: "記録を自動でiCloudに同期", .english: "Automatically sync records to iCloud"],
        "iCloud Sync Notice": [.japanese: "※設定の変更はアプリの次回起動時に反映されます。", .english: "*Changes will take effect on next launch."],
        "iCloudバックアップ": [.japanese: "iCloudバックアップ", .english: "iCloud Backup"],
        "Reset Settings": [.japanese: "設定をリセット", .english: "Reset Settings"],
        "Practice Help": [.japanese: "練習画面のヘルプ", .english: "Practice Help"],
        "Tide Help": [.japanese: "潮位画面のヘルプ", .english: "Tide Help"],
        "RowMode Help": [.japanese: "乗艇画面のヘルプ", .english: "RowMode Help"],
        "Reset Alert Message": [.japanese: "すべての設定をデフォルト値に戻します。この操作は取り消せません。", .english: "Reset all settings to default. This cannot be undone."],
        "Cancel": [.japanese: "キャンセル", .english: "Cancel"],
        "Reset": [.japanese: "リセット", .english: "Reset"],
        "Terms of Service": [.japanese: "利用規約", .english: "Terms of Service"],
        "Credits": [.japanese: "クレジット", .english: "Credits"],
        "Color Theme": [.japanese: "カラーテーマを選択", .english: "Select Color Theme"],
        "SOS Settings": [.japanese: "緊急連絡先設定", .english: "SOS Settings"],
        "Contact Name": [.japanese: "連絡先氏名", .english: "Contact Name"],
        "Phone Number": [.japanese: "電話番号", .english: "Phone Number"],
        "User Name": [.japanese: "使用者の名前", .english: "User Name"],
        "Emergency Contact": [.japanese: "緊急連絡先", .english: "Emergency Contact"],
        "SOS Message Hint": [.japanese: "緊急時に現在地、時刻、バッテリー残量を指定の連絡先へ送信します。", .english: "Sends location, time, and battery level to your emergency contact in case of an emergency."],
        "Location Info": [.japanese: "位置情報", .english: "Location Info"],
        "Battery": [.japanese: "バッテリー", .english: "Battery"],
        "No response. Please check.": [.japanese: "SOS信号が発信されました。確認してください。", .english: "An SOS signal has been sent. Please check."],
        "SOS Warning": [.japanese: "緊急連絡先の未設定", .english: "SOS Not Configured"],
        "SOS Warning Message": [.japanese: "緊急連絡先または使用者氏名が設定されていません。\nこのまま開始しますか？", .english: "Emergency contact or user name is not set.\nDo you want to start anyway?"],
        "SOS Button Warning Message": [.japanese: "緊急連絡先または使用者氏名が設定されていません。\nこのままSOSを発信しますか？", .english: "Emergency contact or user name is not set.\nDo you want to send SOS anyway?"],
        "Set Contact": [.japanese: "設定画面へ", .english: "Set Contact"],
        "Start Anyway": [.japanese: "無視して開始", .english: "Start Anyway"],
        "Send Anyway": [.japanese: "このまま発信", .english: "Send Anyway"],
        "Low Power Mode Warning": [.japanese: "省電力モードが有効なため、画面が暗くなることがあります。", .english: "Screen may dim due to Low Power Mode."],
        "Prevent Screen Dimming": [.japanese: "RowMode中の画面の暗転を防止", .english: "Prevent Screen Dimming during RowMode"],
        "Screen Dimming Warning Hint": [.japanese: "画面を常にONに保ちます。長時間の表示によって画面の焼き付きやバッテリー消耗の原因となる場合があります。", .english: "Keep the screen awake. Long-term usage may cause screen burn-in or battery drain."],
        "Map Type": [.japanese: "マップの種類", .english: "Map Type"],
        "Apple Maps": [.japanese: "Apple Maps", .english: "Apple Maps"],
        "Google Maps": [.japanese: "Google Maps", .english: "Google Maps"],
        "Apple Maps & Google Maps": [.japanese: "両方 (Apple & Google)", .english: "Both (Apple & Google)"],
        
        // MARK: - Subscription / Billing
        "RowPilot Premium": [.japanese: "RowPilot プレミアム", .english: "RowPilot Premium"],
        "Unlock all features and power up your rowing.": [.japanese: "すべての機能を開放して、練習をさらに効率的に。", .english: "Unlock all features and power up your rowing."],
        "Upgrade RowPilot": [.japanese: "RowPilotをアップグレード", .english: "Upgrade RowPilot"],
        "Unlock premium features and reach your potential.": [.japanese: "プレミアム機能を開放して、あなたの可能性を引き出しましょう。\n 全てのプランは1度の購入で永続的に使用できます。", .english: "Unlock premium features and reach your potential. \n All plans are available for lifetime use with a single purchase. "],
        "CURRENT PLAN": [.japanese: "現在のプラン", .english: "CURRENT PLAN"],
        "Individual": [.japanese: "個人向け", .english: "Individual"],
        "For Managers": [.japanese: "マネージャー向け", .english: "For Managers"],
        "For Coaches & Teams": [.japanese: "コーチ・団体向け", .english: "For Coaches & Teams"],
        "Subscriptions": [.japanese: "サブスクリプション", .english: "Subscriptions"],
        "Authentication Error": [.japanese: "認証エラー", .english: "Authentication Error"],
        "Confirm your subscription purchase.": [.japanese: "サブスクリプションの購入を確定します。", .english: "Confirm your subscription purchase."],
        "Please authenticate to complete purchase.": [.japanese: "購入を完了するには認証が必要です。", .english: "Please authenticate to complete purchase."],
        "Plan Details": [.japanese: "プラン詳細", .english: "Plan Details"],
        "Purchase": [.japanese: "購入する", .english: "Purchase"],
        "You are currently subscribed to this plan.": [.japanese: "現在このプランを契約中です。", .english: "You are currently subscribed to this plan."],
        "Included Features": [.japanese: "含まれる機能", .english: "Included Features"],
        "Current Plan": [.japanese: "現在のプラン", .english: "Current Plan"],
        "RowPilot Enterprise": [.japanese: "RowPilot Enterprise", .english: "RowPilot Enterprise"],
        "要問い合わせ": [.japanese: "要問い合わせ", .english: "Contact Us"],
        "基本機能(潮汐確認、GPSレート計、PM5と1:1接続など)": [.japanese: "基本機能(潮汐確認、GPSレート計、PM5と1:1接続など)", .english: "Basic features (tide info, GPS rate meter, PM5 1:1 connection, etc.)"],
        "ForceCurveやStrava同期などプロ向けの機能を開放": [.japanese: "ForceCurveやStrava同期などプロ向けの機能を開放", .english: "Unlock professional features such as ForceCurve and Strava synchronization"],
        "PM5複数台接続＋最大1人のメンバーにプランを共有可能": [.japanese: "PM5複数台接続＋最大1人のメンバーにプランを共有可能", .english: "Connect multiple PM5s + share plan with up to 1 member"],
        "最大3人のメンバーにプラン共有可能。CSV出力、レースビュー等を開放": [.japanese: "最大3人のメンバーにプラン共有可能。CSV出力、レースビュー等を開放", .english: "Share plan with up to 3 members. Unlock CSV export, race view, etc."],
        "大規模導入・独自カスタマイズなど、チームに最適化されたカスタムプラン": [.japanese: "大規模導入・独自カスタマイズなど、チームに最適化されたカスタムプラン", .english: "Customized plan optimized for teams with large-scale deployment & unique modifications."],
        "潮汐情報の確認": [.japanese: "潮汐情報の確認", .english: "Tide Information"],
        "GPSレート計": [.japanese: "GPSレート計", .english: "GPS Stroke Rate"],
        "PM5との1:1接続": [.japanese: "PM5との1:1接続", .english: "PM5 1:1 Connection"],
        "ForceCurveの表示": [.japanese: "ForceCurveの表示", .english: "Force Curve Display"],
        "Stravaとの同期": [.japanese: "Stravaとの同期", .english: "Strava Sync"],
        "ゴーストレース機能": [.japanese: "ゴーストレース機能", .english: "Ghost Race"],
        "PM5と複数台接続機能": [.japanese: "PM5と複数台接続機能", .english: "PM5 Multi-Connection"],
        "リアルタイム一斉トレーニング": [.japanese: "リアルタイム一斉トレーニング", .english: "Real-time Bulk Workout"],
        "最大1名のメンバーとプランを共有": [.japanese: "最大1名のメンバーとプランを共有", .english: "Share plan with up to 1 member"],
        "CSV形式出力": [.japanese: "CSV形式出力", .english: "CSV Export"],
        "レースビュー開放": [.japanese: "レースビュー開放", .english: "Race View Unlock"],
        "高度なアナリティクス": [.japanese: "高度なアナリティクス", .english: "Advanced Analytics"],
        "最大3名のメンバーとプランを共有": [.japanese: "最大3名のメンバーとプランを共有", .english: "Share plan with up to 3 members"],
        "最大5名のメンバーとプランを共有": [.japanese: "最大5名のメンバーとプランを共有", .english: "Share plan with up to 5 members"],
        "最大200名のメンバーとチーム共有": [.japanese: "最大200名のメンバーとチーム共有", .english: "Team sharing with up to 200 members"],
        "RowPilot Organization": [.japanese: "RowPilot Organization", .english: "RowPilot Organization"],
        "Organizationプラン": [.japanese: "Organizationプラン", .english: "Organization Plan"],
        "Organization Plan": [.japanese: "Organizationプラン", .english: "Organization Plan"],
        "中〜大規模チームで共有して使う": [.japanese: "中〜大規模チームで共有して使う", .english: "Share and use in mid-to-large scale teams"],
        "プランの共有 (最大5名)": [.japanese: "プランの共有 (最大5名)", .english: "Plan sharing (up to 5 members)"],
        "最大5人のメンバーにプラン共有可能。チーム共有最大200名、CSV出力、レースビュー等を開放": [.japanese: "最大5人のメンバーにプラン共有可能。チーム共有最大200名、CSV出力、レースビュー等を開放", .english: "Share plan with up to 5 members. Up to 200 team members, CSV export, Race View, etc."],
        "最大5名のメンバーへのプラン共有に加え、最大200名のチーム共有、CSV形式での記録出力や高度なレースビューを開放します。大規模なクラブ・組織のためのプランです。": [.japanese: "最大5名のメンバーへのプラン共有に加え、最大200名のチーム共有、CSV形式での記録出力や高度なレースビューを開放します。大規模なクラブ・組織のためのプランです。", .english: "In addition to plan sharing for up to 5 members and team sharing for up to 200 members, CSV export and advanced Race View are unlocked. This plan is designed for large clubs and organizations."],
        "エンタープライズサポート": [.japanese: "エンタープライズサポート", .english: "Enterprise Support"],
        "チーム人数無制限": [.japanese: "チーム人数無制限", .english: "Unlimited Team Members"],
        "独自カスタマイズ": [.japanese: "独自カスタマイズ", .english: "Custom Modifications"],
        "専用クラウド・SLA保証": [.japanese: "専用クラウド・SLA保証", .english: "Dedicated Cloud & SLA Guarantee"],
        "大規模チーム・団体向け": [.japanese: "大規模チーム・団体向け", .english: "For large teams & organizations"],
        "プランの共有 (無制限)": [.japanese: "プランの共有 (無制限)", .english: "Unlimited Plan Sharing"],
        "お問い合わせください。": [.japanese: "お問い合わせください。", .english: "Please contact us."],
        
        // New sharing limit texts
        "マネージャープランの共有 (1名)": [.japanese: "マネージャープランの共有 (1名)", .english: "Share Manager Plan (1 member)"],
        "マネージャープランの共有 (3名)": [.japanese: "マネージャープランの共有 (3名)", .english: "Share Manager Plan (3 members)"],
        "マネージャープランの共有 (最大5名)": [.japanese: "マネージャープランの共有 (最大5名)", .english: "Share Manager Plan (up to 5 members)"],
        "「マネージャープラン」を1人に共有": [.japanese: "「マネージャープラン」を1人に共有", .english: "Share Manager Plan with 1 member"],
        "「マネージャープラン」を3人に共有": [.japanese: "「マネージャープラン」を3人に共有", .english: "Share Manager Plan with 3 members"],
        "「マネージャープラン」を最大5人に共有": [.japanese: "「マネージャープラン」を最大5人に共有", .english: "Share Manager Plan with up to 5 members"],
        "1人に「マネージャープラン」を共有、30人のメンバーをまとめて管理、AIとテンプレート型の分析機能(準備中)": [.japanese: "1人に「マネージャープラン」を共有、30人のメンバーをまとめて管理、AIとテンプレート型の分析機能(準備中)", .english: "Share Manager Plan with 1 member, manage 30 members, template-based AI analytics (coming soon)"],
        "3人に「マネージャープラン」を共有、3人を管理者に指定、最大50人をメンバー化、AIと対話型の分析機能(準備中)": [.japanese: "3人に「マネージャープラン」を共有、3人を管理者に指定、最大50人をメンバー化、AIと対話型の分析機能(準備中)", .english: "Share Manager Plan with 3 members, specify 3 admins, up to 50 members, interactive AI analytics (coming soon)"],
        "最大5人に「マネージャープラン」を共有、7人を管理者として指定、最大200人をメンバーとして追加、AIと対話型の分析機能": [.japanese: "最大5人に「マネージャープラン」を共有、7人を管理者として指定、最大200人をメンバーとして追加、AIと対話型の分析機能", .english: "Share Manager Plan with up to 5 members, specify 7 admins, up to 200 members, interactive AI analytics"],
        "Contact": [.japanese: "お問い合わせ", .english: "Contact"],
        "Contact Us": [.japanese: "お問い合わせする", .english: "Contact Us"],
        "Location of Issue (Required)": [.japanese: "問題の発生箇所 (必須)", .english: "Location of Issue (Required)"],
        "Inquiry Content (Required)": [.japanese: "お問い合わせ内容 (必須)", .english: "Inquiry Content (Required)"],
        "Email Address (Optional)": [.japanese: "メールアドレス (任意)", .english: "Email Address (Optional)"],
        "Email Description": [.japanese: "返信が必要な場合はご記入ください", .english: "Please enter if you require a response"],
        "Confirm Inquiry": [.japanese: "入力内容の確認", .english: "Confirm Inquiry"],
        "Send with this content": [.japanese: "この内容で送信する", .english: "Send with this content"],
        "Please select": [.japanese: "選択してください", .english: "Please select"],
        "Invalid email address format": [.japanese: "メールアドレスの形式が正しくありません", .english: "Invalid email address format"],
        "Proceed to Confirm": [.japanese: "確認画面へ", .english: "Proceed to Confirm"],
        "Page:": [.japanese: "ページ:", .english: "Page:"],
        "Element:": [.japanese: "要素:", .english: "Element:"],
        "Email:": [.japanese: "メールアドレス:", .english: "Email:"],
        "No input": [.japanese: "入力なし", .english: "No input"],
        "Yes": [.japanese: "含める", .english: "Yes"],
        "No": [.japanese: "含めない", .english: "No"],
        
        // MARK: - Landscape View / Metrics
        "Distance_M": [.japanese: "距離", .english: "Dist"],
        "Time": [.japanese: "時間", .english: "Time"],
        "Pace": [.japanese: "500m ペース", .english: "500m Pace"],
        "SPM": [.japanese: "SPM", .english: "SPM"],
        "Save Record": [.japanese: "記録を保存", .english: "Save Record"],
        "Save Message": [.japanese: "この練習記録を保存しますか？", .english: "Save this session?"],
        "Save": [.japanese: "保存", .english: "Save"],
        "Discard": [.japanese: "破棄", .english: "Discard"],
        "SOS_Press": [.japanese: "長押しで緊急連絡", .english: "Hold for SOS"],
        "SOS_Hold_2s": [.japanese: "2秒間長押し", .english: "Hold for 2s"],
        "SOS_Hold_1_5s": [.japanese: "長押しで緊急連絡", .english: "Hold for SOS"],
        
        "Count": [.japanese: "回数", .english: "Count"],
        "Stop": [.japanese: "停止", .english: "Stop"],
        "Stroke Count": [.japanese: "ストローク数", .english: "Strokes"],
        "Dist/Stroke": [.japanese: "ストロークあたり距離", .english: "Dist/Stroke"],
        "Display Settings": [.japanese: "表示設定", .english: "Display Settings"],
        "Left Element": [.japanese: "左下の表示項目", .english: "Left Display Item"],
        "Right Element": [.japanese: "右下の表示項目", .english: "Right Display Item"],
        "Motion Sensitivity": [.japanese: "モーション感度 (G)", .english: "Motion Sensitivity (G)"],
        
        // MARK: - Portrait View
        "Rowing Mode": [.japanese: "乗艇モード", .english: "Rowing Mode"],
        "Waiting for GPS": [.japanese: "GPS測位中...", .english: "Waiting for GPS..."],
        "Ready": [.japanese: "準備完了", .english: "Ready"],
        
        "Record Detail": [.japanese: "記録詳細", .english: "Record Detail"],
        "Try recording a session": [.japanese: "練習を記録してみましょう", .english: "Try recording a session."],
        "Sort By": [.japanese: "並び替え", .english: "Sort By"],
        "Route": [.japanese: "経路", .english: "Route"],
        "New Tag": [.japanese: "新しいタグ", .english: "New Tag"],
        "No Tags": [.japanese: "タグなし", .english: "No Tags"],
        "No Notes": [.japanese: "メモなし", .english: "No Notes"],
        
        // Record List
        "Records": [.japanese: "練習記録一覧", .english: "History"],
        "No Records": [.japanese: "記録がありません", .english: "No Records"],
        "Fetching information...": [.japanese: "情報取得中...", .english: "Fetching info..."],
        
        // MARK: - common
        "Close": [.japanese: "閉じる", .english: "Close"],
        "Edit": [.japanese: "編集", .english: "Edit"],
        "Done": [.japanese: "完了", .english: "Done"],
        "Notes": [.japanese: "メモ", .english: "Notes"],
        "Tags": [.japanese: "タグ", .english: "Tags"],
        "Add Tag": [.japanese: "タグを追加", .english: "Add Tag"],
        
        // Record Detail
        "Performance": [.japanese: "パフォーマンス", .english: "Performance"],
        "Avg Pace": [.japanese: "平均ペース", .english: "Avg Pace"],
        "Avg SPM": [.japanese: "平均SPM", .english: "Avg SPM"],
        "Avg Speed": [.japanese: "平均速度", .english: "Avg Speed"],
        "Duration": [.japanese: "時間", .english: "Duration"],
        
        // MARK: - Terms View
        "Terms_LastUpdated": [.japanese: "最終更新日: 2026年5月10日", .english: "Last Updated: May 10, 2026"],
        "Term_1_Title": [.japanese: "1. はじめに", .english: "1. Introduction"],
        "Term_1_Content": [.japanese: """
        本利用規約（以下「本規約」といいます。）は、RowPilot（以下「本アプリ」といいます。）の利用条件を定めるものです。
        ユーザーは、本アプリを利用することにより、本規約に同意したものとみなされます。
        また、本アプリは個人により開発されたアプリであり、提供内容は予告なく変更される場合があります。
        """, .english: """
        This Terms of Service ("Terms") defines the conditions for using RowPilot ("App").
        By using the App, you are deemed to have agreed to these Terms.
        This App is developed by an individual, and the content provided may change without notice.
        """],
        "Term_2_Title": [.japanese: "2. 本アプリの目的", .english: "2. Purpose of the App"],
        "Term_2_Content": [.japanese: """
        本アプリは、ローイング、またはそれに関わる練習の記録・分析・振り返りを補助することを目的としたアプリです。
        競技成績の保証、健康・安全の保証を行うものではありません。
        """, .english: """
        The App is intended to assist in recording, analyzing, and reviewing rowing and related training.
        It does not guarantee competitive performance, health, or safety.
        """],
        "Term_3_Title": [.japanese: "3. 安全について", .english: "3. About Safety"],
        "Term_3_Content": [.japanese: """
        本アプリは、水上での使用を想定した機能を含んでいます。
        水上で本アプリを操作する際は、周囲の状況および自身の安全に十分配慮し、危険が生じるおそれがある場合には、直ちに使用を中止してください。
        水上での使用に伴い、端末の紛失や故障等が生じた場合においても、当方は一切の責任を負いません。ユーザー自身の責任においてご利用ください。
        """, .english: """
        The App includes functions intended for use on the water.
        When operating the App on the water, pay close attention to your surroundings and safety. If there is any danger, stop using it immediately.
        We are not responsible for any loss or malfunction of devices during use on the water. Please use it at your own risk.
        """],
        "Term_4_Title": [.japanese: "4. 取得する情報", .english: "4. Information Collected"],
        "Term_4_Content": [.japanese: """
        本アプリは、以下の情報を取得する場合があります。
        •  位置情報（GPS）：練習距離、速度、ペース、経路の記録・表示のため
        •  時刻・経過時間
        •  端末情報（OS種別等、動作確認のため）
        取得する情報は、本アプリの機能提供に必要な範囲に限られます。
        また、これらの情報はすべてデバイス内で安全に処理され、ユーザーの同意なしに外部に送信されることはありません。
        """, .english: """
        The App may collect the following information:
        • Location (GPS): For recording and displaying distance, speed, pace, and routes.
        • Time and elapsed time.
        • Device info (OS type, etc., for operation verification).
        Information collected is limited to what is necessary for the App's functions.
        In addition, since all of this information is safely processed on your device, it is never sent to external sources without user consent.
        """],
        "Term_5_Title": [.japanese: "5. 位置情報の取り扱い", .english: "5. Handling of Location Information"],
        "Term_5_Content": [.japanese: """
        本アプリは、練習距離・速度・経路の記録を目的として、位置情報（GPS）を利用します。
        位置情報の取得は、ユーザーが端末の設定において許可した場合に限り行われます。
        取得された位置情報は、本アプリの機能提供の範囲内でのみ利用され、開発者を含む第三者へ意図せず提供されることはありません。
        ユーザーは、端末の設定により、いつでも位置情報の利用を停止することができます。
        """, .english: """
        The App use Location (GPS) for recording distance, speed and route.
        Location data is only accessed if you grant permission in your device settings.
        Collected data is used only within the App's functions; we do not view, collect, or provide this data to third parties.
        You can stop location usage at any time through your device settings.
        """],
        "Term_6_Title": [.japanese: "6. データの保存", .english: "6. Data Storage"],
        "Term_6_Content": [.japanese: """
        練習記録データは、ユーザーの端末内に保存されます。
        機種変更、アプリ削除等によりデータが消失する可能性がありますが、iCloudにバックアップすることで情報の保持が可能になります。
        データの消失・破損について、当方は責任を負いません。
        """, .english: """
        Training records are saved on your device.
        Data may be lost during device changes or App deletion, but can be preserved via iCloud backup.
        We are not responsible for data loss or corruption.
        """],
        "Term_7_Title": [.japanese: "7. 禁止事項", .english: "7. Prohibited Matters"],
        "Term_7_Content": [.japanese: """
        ユーザーは、本アプリの利用に際し以下の行為を行ってはなりません。
        •  本アプリの目的とは異なった利用
        •  他者の権利・安全を侵害する行為
        •  法令または公序良俗に反する行為
        •  本アプリの運営を妨害する行為
        •  本アプリの解析、改変、リバースエンジニアリングを目的とした行為
        """, .english: """
        Users must not perform the following:
        • Use for purposes other than intended.
        • Infringing on the rights or safety of others.
        • Actions against laws or public order.
        • Interfering with the App's operation.
        • Analysis, modification, or reverse engineering of the App.
        """],
        "Term_8_Title": [.japanese: "8. 免責事項", .english: "8. Disclaimer"],
        "Term_8_Content": [.japanese: """
        本アプリの利用は、ユーザー自身の責任において行われるものとします。
        本アプリ内容の正確性・完全性・有用性について、当方は保証しません。
        本アプリの利用により生じたいかなる損害についても、当方は責任を負いません。
        SOS機能は、補助的な機能であり、警察・消防等への緊急通報手段を代替するものではありません。
        本機能の作動遅延、未作動、通知未達等により生じたいかなる損害についても、当方は責任を負いません。
        """, .english: """
        Use of the App is at the user's own responsibility.
        We do not guarantee the accuracy, completeness, or usefulness of the App content.
        We are not liable for any damages resulting from using the App.
        The SOS function is supplementary and does not replace emergency reporting (police, fire).
        We are not liable for damages due to delays, failures, or missed notifications of this function.
        """],
        "Term_9_Title": [.japanese: "9. サービス内容の変更・終了", .english: "9. Changes/Termination of Service"],
        "Term_9_Content": [.japanese: """
        開発者はユーザーへの事前通知なく、本アプリの内容を変更または提供を終了することがあります。
        """, .english: """
        The developer may change or terminate App content/provision without prior notice.
        """],
        "Term_10_Title": [.japanese: "10. 規約の変更", .english: "10. Changes to Terms"],
        "Term_10_Content": [.japanese: """
        本規約は、必要に応じて変更されることがあります。
        変更後の規約は、本アプリ内または適切な方法で周知された時点から効力を生じます。
        """, .english: """
        These Terms may be changed as needed.
        Revised Terms take effect once announced within the App or via appropriate methods.
        """],
        "Term_11_Title": [.japanese: "11. 準拠法・裁判管轄", .english: "11. Governing Law/Jurisdiction"],
        "Term_11_Content": [.japanese: """
        本規約の解釈にあたっては、日本法を準拠法とします。本アプリに関して紛争が生じた場合には、当方の所在地を管轄する裁判所を専属的合意管轄とします。
        """, .english: """
        These Terms are governed by Japanese law. Any disputes regarding the App shall fall under the exclusive jurisdiction of the court overseeing the developer's location.
        """],
        
        // MARK: - Splash View
        "Navigate Your Performance": [.japanese: "Navigate Your Performance", .english: "Navigate Your Performance"],
        
        // MARK: - PM5 Manager View
        "Bluetooth ON": [.japanese: "Bluetooth ON", .english: "Bluetooth ON"],
        "Bluetooth OFF": [.japanese: "Bluetooth OFF", .english: "Bluetooth OFF"],
        "Scanning PM5": [.japanese: "PM5をスキャン", .english: "Scan PM5"],
        "Stop Scan": [.japanese: "スキャン停止", .english: "Stop Scan"],
        "Discovered PM5": [.japanese: "検出済みのPM5", .english: "Discovered PM5"],
        "Connecting...": [.japanese: "接続中...", .english: "Connecting..."],
        "Add": [.japanese: "追加", .english: "Add"],
        "Connected PM5": [.japanese: "追加済みPM5", .english: "Registered PM5"],
        "Add PM5 Message": [.japanese: "PM5を追加してください", .english: "Please add PM5"],
        "Connected": [.japanese: "接続済み", .english: "Connected"],
        "Delete": [.japanese: "削除", .english: "Remove"],
        "Next": [.japanese: "次へ", .english: "Next"],
        "PM5 Manager": [.japanese: "マネージャーモード", .english: "Manager Mode"],
        "Sending CSAFE...": [.japanese: "CSAFEコマンド送信中...", .english: "Sending CSAFE Commands..."],
        "Reconnecting": [.japanese: "再接続中...", .english: "Reconnecting..."],
        "Dashboard": [.japanese: "ダッシュボード", .english: "Dashboard"],
        "Race View": [.japanese: "レースビュー", .english: "Race View"],
        "Target Distance": [.japanese: "目標距離", .english: "Target Distance"],
        "Target Time": [.japanese: "目標時間", .english: "Target Time"],
        "Target Calories": [.japanese: "目標カロリー", .english: "Target Calories"],
        "Elapsed": [.japanese: "経過時間", .english: "Elapsed"],
        "Active": [.japanese: "接続中", .english: "Active"],
        "Repeat": [.japanese: "もう一度", .english: "Repeat"],
        "Repeat Workout": [.japanese: "ワークアウトを繰り返す", .english: "Repeat Workout"],
        "Save and Repeat": [.japanese: "保存してもう一度", .english: "Save and Repeat"],
        "Discard and Repeat": [.japanese: "破棄してもう一度", .english: "Discard and Repeat"],
        "Would you like to save this workout record?": [.japanese: "このワークアウト記録を保存しますか？", .english: "Would you like to save this workout record?"],
        "Would you like to save all connected erg records?": [.japanese: "接続中のすべてのエルゴ記録を保存しますか？", .english: "Would you like to save all connected erg records?"],
        "Change": [.japanese: "変更", .english: "Change"],
        "Reset Lock": [.japanese: "リセットロック", .english: "Reset Lock"],
        "Locked. Please press and hold the lock button for 1.5 seconds.": [.japanese: "ロックされています。鍵ボタンを1.5秒間押し続けてください。", .english: "Locked. Press and hold the lock button for 1.5 seconds."],
        
        // MARK: - Practice View
        "Connection Status": [.japanese: "接続ステータス", .english: "Connection Status"],
        "Connected: RowErg": [.japanese: "接続中: Concept2 RowErg", .english: "Connected: Concept2 RowErg"],
        "Machine State": [.japanese: "マシン状態:", .english: "Machine State:"],
        "Disconnect": [.japanese: "接続解除", .english: "Disconnect"],
        "NFC Connect": [.japanese: "NFC 接続", .english: "NFC Connect"],
        "Discovered Devices": [.japanese: "検出済みデバイス", .english: "Discovered Devices"],
        "Live Data": [.japanese: "ライブデータ", .english: "Live Data"],
        "Raw Data details": [.japanese: "生データ詳細", .english: "Raw Data details"],
        "Manager Mode": [.japanese: "マネージャーモード", .english: "Manager Mode"],
        "Manager Mode Desc": [.japanese: "複数PM5を接続してワークアウトを一括設定", .english: "Sync workout setup for multiple PM5s"],
        "Research": [.japanese: "リサーチ", .english: "Research"],
        "Practice(Dev)": [.japanese: "練習", .english: "Practice"],
        
        // MARK: - Workout Setup
        "Other Workouts (Workout List)": [.japanese: "その他のワークアウト（ワークアウト一覧へ）", .english: "Other Workouts (Go to Workout List)"],
        "Select Workout Type": [.japanese: "ワークアウト種目を選択", .english: "Select Workout Type"],
        "Single Distance": [.japanese: "単一距離", .english: "Single Distance"],
        "Single Time": [.japanese: "単一時間", .english: "Single Time"],
        "Single Calories": [.japanese: "単一カロリー", .english: "Single Calories"],
        "Workout Setup": [.japanese: "ワークアウト設定", .english: "Workout Setup"],
        "Distance Setup": [.japanese: "距離設定", .english: "Distance Setup"],
        "Time Setup": [.japanese: "時間設定", .english: "Time Setup"],
        "Fixed Interval": [.japanese: "不変インターバル", .english: "Fixed Interval"],
        "Variable Interval": [.japanese: "可変インターバル", .english: "Variable Interval"],
        "Edit Interval": [.japanese: "インターバル編集", .english: "Edit Interval"],
        "Add Interval": [.japanese: "+ インターバル追加", .english: "+ Add Interval"],
        "Add Next Interval": [.japanese: "+ 次のインターバル", .english: "+ Add Next Interval"],
        "Set Distance": [.japanese: "設定距離 (m)", .english: "Set Distance (m)"],
        "Distance Range": [.japanese: "※ 対応レンジ: 100m 〜 60,000m", .english: "Range: 100m - 60,000m"],
        "Interval Distance": [.japanese: "インターバル距離", .english: "Interval Distance"],
        "Interval Time": [.japanese: "インターバル時間", .english: "Interval Time"],
        "Rest Duration (Max 9:55)": [.japanese: "休憩時間 (最大 9:55)", .english: "Rest Duration (Max 9:55)"],
        "Target Pace": [.japanese: "目標ペース", .english: "Target Pace"],
        "Send to PM5": [.japanese: "PM5に送信", .english: "Send to PM5"],
        "Send to all PM5s": [.japanese: "全PM5に送信", .english: "Send to all PM5s"],
        "Min Time Message": [.japanese: "※ 最短設定時間は20秒です", .english: "Min duration is 20s"],
        "Bulk Send Message": [.japanese: "台のPM5に一括送信", .english: "sync to PM5s"],
        "Remaining": [.japanese: "残り", .english: "Remaining"],
        "Finish": [.japanese: "終了", .english: "FINISH"],
        "Practice Workout": [.japanese: "練習ワークアウト", .english: "PRACTICE WORKOUT"],
        "Max connection limit is 10 devices": [.japanese: "接続できるデバイスは最大10台までです", .english: "Max connection limit is 10 devices"],
        
        // MARK: - Manager Session Custom Labels
        "Save 0-Record PM5s": [.japanese: "記録が0のPM5も残す", .english: "Save 0-Record PM5s"],
        "Manager Session Detail": [.japanese: "マネージャーモード詳細", .english: "Manager Session Detail"],
        "Connected Devices": [.japanese: "接続デバイス一覧", .english: "Connected Devices"],
        "Connected PM5s": [.japanese: "接続中のPM5", .english: "Connected PM5s"],
        "Devices": [.japanese: "台のデバイス", .english: " Devices"],
        
        // MARK: - Sort Order
        "Sort_Date_Desc": [.japanese: "日付（新しい順）", .english: "Date (Newest)"],
        "Sort_Date_Asc": [.japanese: "日付（古い順）", .english: "Date (Oldest)"],
        "Sort_Dist_Desc": [.japanese: "距離（短い順）", .english: "Dist (Shortest)"],
        "Sort_Duration_Desc": [.japanese: "時間（短い順）", .english: "Time (Shortest)"],
        
        // MARK: - Credits
        "Special Thanks": [.japanese: "協力者", .english: "Special Thanks"],
        "Development Environment": [.japanese: "開発環境", .english: "Dev Environment"],
        "General Assistant": [.japanese: "メインアシスタント", .english: "Main Assistant"],
        "Code Assistant": [.japanese: "開発", .english: "Coding"],
        "Drawing Assistant": [.japanese: "画像生成", .english: "Design"],
        "Mechanical": [.japanese: "機械", .english: "Mechanical"],
        "Information": [.japanese: "情報", .english: "Information"],
        "Civil Engineering": [.japanese: "都市", .english: "Civil"],
        "Architecture": [.japanese: "建築", .english: "Architecture"],
        "Design": [.japanese: "デザイン", .english: "Design"],
        "Advisor": [.japanese: "顧問・外部コーチ", .english: "Advisor"],
        
        // MARK: - Subscription Locks
        "Force Curve is Locked": [.japanese: "フォースカーブはロックされています", .english: "Force Curve is Locked"],
        "Upgrade to Pro to analyze your rowing form in real-time.": [.japanese: "Proプランにアップグレードして、リアルタイムでローイングフォームを分析しましょう。", .english: "Upgrade to Pro to analyze your rowing form in real-time."],
        "Unlock Force Curve": [.japanese: "フォースカーブを解放", .english: "Unlock Force Curve"],
        "Requires Manager Plan": [.japanese: "マネジャープランが必要です", .english: "Requires Manager Plan"],
        "Race View is Locked": [.japanese: "レースビューはロックされています", .english: "Race View is Locked"],
        "Upgrade to RowPilot MAX to visualize real-time racing, competitive leaderboards, and detailed gap tracking.": [.japanese: "RowPilot MAXにアップグレードして、リアルタイムレース、順位表、タイム差表示を解放しましょう。", .english: "Upgrade to RowPilot MAX to visualize real-time racing, competitive leaderboards, and detailed gap tracking."],
        "Unlock Race View (MAX)": [.japanese: "レースビューを解放 (MAX)", .english: "Unlock Race View (MAX)"],
        "Ghost Race is Locked": [.japanese: "ゴーストレースはロックされています", .english: "Ghost Race is Locked"],
        "Upgrade to Pro or above to race against your past indoor records in real-time.": [.japanese: "Proプラン以上にアップグレードして、過去の屋内練習記録とリアルタイムで競い合いましょう。", .english: "Upgrade to Pro or above to race against your past indoor records in real-time."],
        "Unlock Ghost Race": [.japanese: "ゴーストレースを解放", .english: "Unlock Ghost Race"],
        "Select Past Record for Race": [.japanese: "過去の練習記録を選択", .english: "Select Past Record for Race"],
        "No past indoor records found.": [.japanese: "過去の屋内練習記録が見つかりません。", .english: "No past indoor records found."],
        "Manager Session (%d devices)": [.japanese: "マネージャーセッション (%d台のデバイス)", .english: "Manager Session (%d devices)"],
        "Race with Past Self": [.japanese: "過去の自分とレース", .english: "Race with Past Self"],
        "Opponent: %@ (%.0fm)": [.japanese: "対戦相手: %@ (%.0fm)", .english: "Opponent: %@ (%.0fm)"],
        
        // MARK: - Sharing & Import
        "About Export Formats": [.japanese: "出力形式について", .english: "About Export Formats"],
        "rowpilot_desc": [.japanese: "【.rowpilot形式】\nRowPilotアプリ間で完全なデータを共有するための専用形式です。グラフ用の時系列データ（ストロークごとの情報）や位置情報、クルー情報などが全て含まれます。他の端末のRowPilotアプリへデータ移行・インポートしたい場合に選択してください。", .english: "[.rowpilot format]\nA proprietary format for sharing complete data between RowPilot apps. It includes all time-series data for graphs (stroke-by-stroke info), location data, and crew details. Choose this if you want to import/transfer data to RowPilot on another device."],
        "csv_desc": [.japanese: "【.csv形式 (RowPilot MAX限定)】\nExcelやGoogleスプレッドシートなどの表計算ソフトで管理するための一般的な形式です。日付、時間、距離、平均ペース、平均SPM、デバイス情報、メモなどのサマリーのみが保存されます。PC等で複数の練習データを一覧化して管理したい場合に適しています。", .english: "[.csv format (RowPilot MAX only)]\nA standard format for managing data in spreadsheets like Excel or Google Sheets. It saves only the workout summary (date, duration, distance, average pace, SPM, device info, and notes). Best for logging and tracking multiple records on a computer."],
        "Share RowPilot Data (.rowpilot)": [.japanese: "RowPilotデータとして共有 (.rowpilot)", .english: "Share RowPilot Data (.rowpilot)"],
        "Export CSV (.csv)": [.japanese: "CSV形式でエクスポート (.csv)", .english: "Export CSV (.csv)"],
        "Export CSV (.csv) 👑": [.japanese: "CSV形式でエクスポート (.csv) 👑", .english: "Export CSV (.csv) 👑"],
        "RowPilot MAX Exclusive": [.japanese: "RowPilot MAX限定機能", .english: "RowPilot MAX Exclusive"],
        "CSV export is a RowPilot MAX exclusive feature. Upgrade to unlock this feature.": [.japanese: "CSV出力はRowPilot MAX限定機能です。アップグレードして機能を開放しましょう。", .english: "CSV export is a RowPilot MAX exclusive feature. Upgrade to unlock this feature."],
        "View Plans": [.japanese: "プランを見る", .english: "View Plans"],
        "Share Confirmation": [.japanese: "共有の確認", .english: "Share Confirmation"],
        "Share to \"%@\"?": [.japanese: "\"%@\" に共有しますか？", .english: "Share to \"%@\"?"],
        "Sharing": [.japanese: "ワークアウト共有", .english: "Workout Sharing"],
        "Sharing Name": [.japanese: "共有時の名前", .english: "Sharing Name"],
        "Sharing Name Hint": [.japanese: "※ 強制ではありませんが、Team、MAXプランでチーム共有を受ける際に必要となります。", .english: "* Not required, but needed when receiving team sharing under Team/MAX plans."],
        "Share": [.japanese: "共有", .english: "Share"],
        "Share Workout": [.japanese: "ワークアウトを共有", .english: "Share Workout"],
        "Auto Share After Save": [.japanese: "保存後に共有を提案", .english: "Suggest Sharing After Save"],
        "Auto Share Desc": [.japanese: "マネージャーモードで保存した後、各デバイスへの共有を提案します", .english: "Suggest sharing to each device after saving in Manager Mode"],
        "Import Behavior": [.japanese: "受信時の動作", .english: "Import Behavior"],
        "Import Behavior Desc": [.japanese: "他のデバイスから共有されたワークアウトの受信方法を選択します", .english: "Choose how to handle workouts shared from other devices"],
        "自動インポート": [.japanese: "自動インポート", .english: "Auto Import"],
        "毎回確認": [.japanese: "毎回確認", .english: "Ask Each Time"],
        "受信しない": [.japanese: "受信しない", .english: "Reject"],
        "Skip": [.japanese: "スキップ", .english: "Skip"],
        
        // MARK: - Invite Code & Share Request
        "Team & MAX Management": [.japanese: "Team & MAX 管理", .english: "Team & MAX Management"],
        "Teammates can share RowPilot Manager features.": [.japanese: "チームメンバーにManagerプランを共有できます。", .english: "Teammates can share RowPilot Manager features."],
        "SHARING SLOTS": [.japanese: "共有枠", .english: "SHARING SLOTS"],
        "Shared Members": [.japanese: "共有中のメンバー", .english: "Shared Members"],
        "Manager Sharing": [.japanese: "Manager Plan 共有管理", .english: "Manager Sharing"],
        "Manager Plan Sharing Help": [.japanese: "共有についてのヘルプ", .english: "Manager Plan Sharing Help"],
        "Workout Imported": [.japanese: "ワークアウトをインポートしました", .english: "Workout Imported"],
        "Duplicate Record": [.japanese: "この記録は既にインポート済みです", .english: "This record has already been imported"],
        "Import Failed": [.japanese: "インポートに失敗しました", .english: "Import Failed"],
        "Save Results": [.japanese: "結果を保存", .english: "Save Results"],
        "Finish Workout": [.japanese: "ワークアウトを終了", .english: "Finish Workout"],
        "Finish without saving": [.japanese: "保存せずに終了", .english: "Finish without saving"],
        "Save and Finish": [.japanese: "保存して終了", .english: "Save and Finish"],
        "Are you sure you want to finish without saving?": [.japanese: "保存せずに終了してよろしいですか？", .english: "Are you sure you want to finish without saving?"],
        "Would you like to save current results before repeating?": [.japanese: "繰り返す前に現在の結果を保存しますか？", .english: "Would you like to save current results before repeating?"],
        "Back": [.japanese: "戻る", .english: "Back"],
        "Manager Session": [.japanese: "マネージャーセッション", .english: "Manager Session"],
        "History": [.japanese: "履歴", .english: "History"],
        "Workout Details": [.japanese: "ワークアウト詳細", .english: "Workout Details"],
        
        // MARK: - Deletion Alerts
        "Delete All Workouts": [.japanese: "すべてのワークアウトを消去", .english: "Delete All Workouts"],
        "Delete All Alert Message": [.japanese: "すべてのワークアウトデータを消去しますか？この操作は取り消せません。", .english: "Are you sure you want to delete all workout data? This action cannot be undone."],
        "Delete Record": [.japanese: "記録の削除", .english: "Delete Record"],
        "Delete Record Message": [.japanese: "この記録を削除しますか？\n削除されたデータは復元できません。", .english: "Are you sure you want to delete this record? This action cannot be undone."],
        "Delete Session Message": [.japanese: "このセッション内のすべての記録（%d件）を削除しますか？\n削除されたデータは復元できません。", .english: "Are you sure you want to delete all %d records in this session? This action cannot be undone."],
        
        // MARK: - Rigging & Oars
        "Port": [.japanese: "バウサイド (Port)", .english: "Port (Bow)"],
        "Starboard": [.japanese: "ストサイド (Stbd)", .english: "Starboard (Str)"],
        "Rigging & Oars": [.japanese: "艇・オール調整", .english: "Rigging & Oars"],
        "Single Scull Default": [.japanese: "シングルスカル初期設定", .english: "Single Scull Default"],
        "Oar Rigging": [.japanese: "オールの調整", .english: "Oar Rigging"],
        "Boat Rigging": [.japanese: "艇のリギング", .english: "Boat Rigging"],
        "Total Length": [.japanese: "全長", .english: "Total Length"],
        "Inboard": [.japanese: "インボード", .english: "Inboard"],
        "Outboard": [.japanese: "アウトボード", .english: "Outboard"],
        "Blade Type": [.japanese: "ブレード形状", .english: "Blade Type"],
        "Span / Spread": [.japanese: "スパン / スプレッド", .english: "Span / Spread"],
        "Work Height": [.japanese: "ハイト (シート面〜)", .english: "Work Height"],
        "Pitch": [.japanese: "ピッチ (度)", .english: "Pitch"],
        "Footstretch": [.japanese: "フットストレッチ", .english: "Footstretch"],
        "Scull": [.japanese: "スカル", .english: "Scull"],
        "Sweep": [.japanese: "スイープ", .english: "Sweep"],
        "Setup Name": [.japanese: "設定名", .english: "Setup Name"],
        "Boat Type": [.japanese: "艇種", .english: "Boat Type"],
        "Oar Type": [.japanese: "オール形式", .english: "Oar Type"],
        "Save Setup": [.japanese: "設定を保存", .english: "Save Setup"],
        "Create New Setup": [.japanese: "新規リギング設定作成", .english: "Create New Setup"],
        "Edit Setup": [.japanese: "リギング設定編集", .english: "Edit Setup"],
        "Active Setup": [.japanese: "使用中の設定", .english: "Active Setup"],
        "Top View": [.japanese: "上部からの視点 (真上)", .english: "Top View (Overhead)"],
        "Diagonal View": [.japanese: "斜めからの視点 (立体プレビュー)", .english: "Diagonal View (3D Preview)"],
        "Side View": [.japanese: "横からの視点 (ハイト/ピッチ)", .english: "Side View (Height & Pitch)"],
        "Use Active": [.japanese: "適用する", .english: "Use Active"],
        "Total Length Highlight Description": [.japanese: "全長: ブレードの先端からハンドルの端までの全体の長さです。", .english: "Total Length: Overall length from the blade tip to the handle end."],
        "Inboard Highlight Description": [.japanese: "インボード: カラー(ボタン)からハンドルの端までの内側の長さです。", .english: "Inboard: Inward length from the collar (button) to the handle end."],
        "Outboard Highlight Description": [.japanese: "アウトボード: カラー(ボタン)からブレードの先端までの外側の長さです。", .english: "Outboard: Outward length from the collar (button) to the blade tip."],
        "Span Highlight Description": [.japanese: "スパン/スプレッド: 左右のピン間隔(スカル)または艇の中心線からピンまでの距離(スイープ)です。", .english: "Span/Spread: Distance between pins (scull) or centerline to pin (sweep)."],
        "Height Highlight Description": [.japanese: "ハイト (シート面から): シートの最も低い位置からゲート(クラッチ)底面までの垂直高さです。", .english: "Work Height: Vertical height from the lowest point of seat to bottom of oarlock."],
        "Pitch Highlight Description": [.japanese: "ピッチ: ゲート(クラッチ)の垂直に対する傾き角度（通常は艇尾・外側へ4°〜6°）です。", .english: "Pitch: Angle of oarlock pin relative to vertical (normally 4° to 6°)."],
        "Footstretch Highlight Description": [.japanese: "フットストレッチ: ピン中心線からフットプレート(ヒール部)までの前後位置です。", .english: "Footstretch: Distance from pin centerline to the heels of footplate."],
        "Active Setup Indicator": [.japanese: "使用中", .english: "Active"],
        "No Rigging Setups": [.japanese: "保存されたリギング設定はありません", .english: "No saved rigging setups."],
        "Rigging Setups List": [.japanese: "リギング設定一覧", .english: "Rigging Setups"],
        "Boat Rigging Profile": [.japanese: "艇・オール設定", .english: "Rigging Profile"],
        "Sleeve Pitch": [.japanese: "スリーブピッチ", .english: "Sleeve Pitch"],
        "Sleeve Pitch Highlight Description": [.japanese: "スリーブピッチ: スリーブ面に対するピッチ角（通常は0°または4°）です。", .english: "Sleeve Pitch: Angle of the sleeve face relative to the blade plane (normally 0° or 4°)."],
        "Footplate Angle": [.japanese: "フットプレート角度", .english: "Footplate Angle"],
        "Footplate Height": [.japanese: "ヒールデプス", .english: "Heel Depth"],
        "Footplate Angle Highlight Description": [.japanese: "フットプレート角度: フットプレート(靴)の水平面に対する傾き（通常38°〜45°）です。", .english: "Footplate Angle: Angle of the footplate/shoes relative to horizontal (typically 38°-45°)."],
        "Footplate Height Highlight Description": [.japanese: "ヒールデプス: シート面からヒールカップ(かかと受け)底面までの垂直方向の深さです。(平均値は10〜18cmです。)", .english: "Heel Depth: Vertical depth from seat plane to bottom of heels (typical average is 10-18 cm)."],
        "Footplate": [.japanese: "フットプレート", .english: "Footplate"],
        "Lateral Pitch": [.japanese: "ラテラルピッチ", .english: "Lateral Pitch"],
        "Grip Diameter": [.japanese: "グリップ径", .english: "Grip Diameter"],
        "Lateral Pitch Highlight Description": [.japanese: "ラテラルピッチ: Concept2製オールロックで使用するブッシュ（4/4、5/3、6/2、7/1）の選択値です。オールのピッチ角を微調整します。", .english: "Lateral Pitch: Concept2 oarlock bushing insert setting (4/4, 5/3, 6/2, 7/1) used to adjust the oar pitch angle."],
        "Grip Diameter Highlight Description": [.japanese: "グリップ径: オールハンドルの握り部分の直径（通常は34mm〜37mm）です。", .english: "Grip Diameter: Diameter of the oar handle grip (typically 34mm to 37mm)."],
        "Rigging Settings": [.japanese: "リギング設定", .english: "Rigging Settings"],
        "Show all values when idle": [.japanese: "全体の値を表示する", .english: "Show all values when idle"],
        "Footstretch Measurement": [.japanese: "フットストレッチ計測法", .english: "Footstretch Measurement"],
        "From Heel": [.japanese: "踵から測る", .english: "From Heel"],
        "From Shoe Center": [.japanese: "中心から測る", .english: "From Shoe Center"],
        "Seat Position": [.japanese: "シート位置", .english: "Seat Position"],
        "Seat Position Highlight Description": [.japanese: "シート位置: ピン中心線からシートまでの前後位置です。", .english: "Seat Position: Longitudinal distance from the pin centerline to the seat."],
        "Customize how rigging values are displayed in the preview diagrams.": [.japanese: "プレビュー画面におけるリギング値の表示方法をカスタマイズします。", .english: "Customize how rigging values are displayed in the preview diagrams."],
        "Displays configured values on the diagrams even when no field is selected.": [.japanese: "編集していない時でも、艇の各パーツに設定した寸法を表示します。", .english: "Displays configured values on the diagrams even when no field is selected."],
        "Select the reference point for measuring footstretch length.": [.japanese: "フットストレッチ長を測定する際の基準点を選択します。", .english: "Select the reference point for measuring footstretch length."],

        // MARK: - Auto Added
        "10艇": [.japanese: "10艇", .english: "10艇"],
        "1:1の接続が成立している場合リストに表示されません。": [.japanese: "1:1の接続が成立している場合リストに表示されません。", .english: "1:1の接続が成立している場合リストに表示されません。"],
        "1:1接続では重くならないはずなのでマネージャーモードの事になると思います。": [.japanese: "1:1接続では重くならないはずなのでマネージャーモードの事になると思います。", .english: "1:1接続では重くならないはずなのでマネージャーモードの事になると思います。"],
        "1:1通信時 (シングルモード)": [.japanese: "1:1通信時 (シングルモード)", .english: "1:1通信時 (シングルモード)"],
        "1:複数通信 (マネージャーモード)時": [.japanese: "1:複数通信 (マネージャーモード)時", .english: "1:複数通信 (マネージャーモード)時"],
        "1分おきに更新": [.japanese: "1分おきに更新", .english: "1分おきに更新"],
        "1列 (リスト表示)": [.japanese: "1列 (リスト表示)", .english: "1列 (リスト表示)"],
        "2列 (グリッド)": [.japanese: "2列 (グリッド)", .english: "2列 (グリッド)"],
        "2艇": [.japanese: "2艇", .english: "2艇"],
        "3列 (グリッド)": [.japanese: "3列 (グリッド)", .english: "3列 (グリッド)"],
        "8台の相互通信の成功を収めることができました。": [.japanese: "8台の相互通信の成功を収めることができました。", .english: "8台の相互通信の成功を収めることができました。"],
        "AIと対話しながら続けていても埒が明かず、": [.japanese: "AIと対話しながら続けていても埒が明かず、", .english: "AIと対話しながら続けていても埒が明かず、"],
        "Auto (1/5)": [.japanese: "Auto (1/5)", .english: "Auto (1/5)"],
        "Ave./500m": [.japanese: "Ave./500m", .english: "Ave./500m"],
        "CSV形式での記録出力": [.japanese: "CSV形式での記録出力", .english: "CSV形式での記録出力"],
        "Calories": [.japanese: "Calories", .english: "Calories"],
        "Calories Range": [.japanese: "Calories Range", .english: "Calories Range"],
        "Calories Setup": [.japanese: "Calories Setup", .english: "Calories Setup"],
        "Centerline": [.japanese: "Centerline", .english: "Centerline"],
        "Comminucation Architecture v1の作成": [.japanese: "Comminucation Architecture v1の作成", .english: "Comminucation Architecture v1の作成"],
        "Comminucation Architecture v2の適用": [.japanese: "Comminucation Architecture v2の適用", .english: "Comminucation Architecture v2の適用"],
        "Comminucation Architecture v3.1の適用": [.japanese: "Comminucation Architecture v3.1の適用", .english: "Comminucation Architecture v3.1の適用"],
        "Comminucation Architecture v4の適用": [.japanese: "Comminucation Architecture v4の適用", .english: "Comminucation Architecture v4の適用"],
        "Concept2のPM5とのコミュニケーションドキュメントを読み漁り、": [.japanese: "Concept2のPM5とのコミュニケーションドキュメントを読み漁り、", .english: "Concept2のPM5とのコミュニケーションドキュメントを読み漁り、"],
        "Concept2のRyanさん": [.japanese: "Concept2のRyanさん", .english: "Concept2のRyanさん"],
        "Configuring...": [.japanese: "Configuring...", .english: "Configuring..."],
        "Connected · RowErg": [.japanese: "Connected · RowErg", .english: "Connected · RowErg"],
        "Current Location": [.japanese: "Current Location", .english: "Current Location"],
        "Diff:": [.japanese: "Diff:", .english: "Diff:"],
        "Don't Save": [.japanese: "Don't Save", .english: "Don't Save"],
        "Erg Practice": [.japanese: "Erg Practice", .english: "Erg Practice"],
        "ErgDataからのアップデートか、USBケーブルを用いて更新してください。": [.japanese: "ErgDataからのアップデートか、USBケーブルを用いて更新してください。", .english: "ErgDataからのアップデートか、USBケーブルを用いて更新してください。"],
        "Explanation of actions available on this screen.": [.japanese: "Explanation of actions available on this screen.", .english: "Explanation of actions available on this screen."],
        "Force Curve": [.japanese: "Force Curve", .english: "Force Curve"],
        "Force Curve の表示": [.japanese: "Force Curve の表示", .english: "Force Curve の表示"],
        "ForceCurveの可視化やゴーストレース機能、Stravaとの連携（準備中）など、より深いパフォーマンス分析が可能になります。個人アスリートに最適なプランです。": [.japanese: "ForceCurveの可視化やゴーストレース機能、Stravaとの連携（準備中）など、より深いパフォーマンス分析が可能になります。個人アスリートに最適なプランです。", .english: "ForceCurveの可視化やゴーストレース機能、Stravaとの連携（準備中）など、より深いパフォーマンス分析が可能になります。個人アスリートに最適なプランです。"],
        "ForceCurveの実装。": [.japanese: "ForceCurveの実装。", .english: "ForceCurveの実装。"],
        "GPSレート計の代わりとなる、": [.japanese: "GPSレート計の代わりとなる、", .english: "GPSレート計の代わりとなる、"],
        "GPSレート計は、艇速やストロークテンポなどの重要な指標をリアルタイムで計測できる便利なツールですが、": [.japanese: "GPSレート計は、艇速やストロークテンポなどの重要な指標をリアルタイムで計測できる便利なツールですが、", .english: "GPSレート計は、艇速やストロークテンポなどの重要な指標をリアルタイムで計測できる便利なツールですが、"],
        "Ghost": [.japanese: "Ghost", .english: "Ghost"],
        "Ghostとの差:": [.japanese: "Ghostとの差:", .english: "Ghostとの差:"],
        "Heel Depth": [.japanese: "Heel Depth", .english: "Heel Depth"],
        "Height": [.japanese: "Height", .english: "Height"],
        "Help": [.japanese: "Help", .english: "Help"],
        "H先生": [.japanese: "H先生", .english: "H先生"],
        "Interval Calories": [.japanese: "Interval Calories", .english: "Interval Calories"],
        "Interval Setup": [.japanese: "Interval Setup", .english: "Interval Setup"],
        "Iコーチ": [.japanese: "Iコーチ", .english: "Iコーチ"],
        "Lateral Pitch (Rear View)": [.japanese: "Lateral Pitch (Rear View)", .english: "Lateral Pitch (Rear View)"],
        "Manage Teammates": [.japanese: "Manage Teammates", .english: "Manage Teammates"],
        "Manager Dashboard Help": [.japanese: "Manager Dashboard Help", .english: "Manager Dashboard Help"],
        "Manager Plan 共有申請": [.japanese: "Manager Plan 共有申請", .english: "Manager Plan 共有申請"],
        "Manager Plan共有": [.japanese: "Manager Plan共有", .english: "Manager Plan共有"],
        "Managerプランの共有を要求しています": [.japanese: "Managerプランの共有を要求しています", .english: "Managerプランの共有を要求しています"],
        "Managerプランをチームメンバーに共有します。": [.japanese: "Managerプランをチームメンバーに共有します。", .english: "Managerプランをチームメンバーに共有します。"],
        "Manual": [.japanese: "Manual", .english: "Manual"],
        "Min duration is 20s": [.japanese: "Min duration is 20s", .english: "Min duration is 20s"],
        "NFC": [.japanese: "NFC", .english: "NFC"],
        "No Active Rigging Setup": [.japanese: "No Active Rigging Setup", .english: "No Active Rigging Setup"],
        "No detailed data available": [.japanese: "No detailed data available", .english: "No detailed data available"],
        "OK": [.japanese: "OK", .english: "OK"],
        "Oar": [.japanese: "Oar", .english: "Oar"],
        "O先生": [.japanese: "O先生", .english: "O先生"],
        "PM5 編集": [.japanese: "PM5 編集", .english: "PM5 編集"],
        "PM5 複数台同時接続": [.japanese: "PM5 複数台同時接続", .english: "PM5 複数台同時接続"],
        "PM5との通信やUIデザインについて": [.japanese: "PM5との通信やUIデザインについて", .english: "PM5との通信やUIデザインについて"],
        "PM5と接続し、屋外だけでなく屋内での記録ができるようにすると思い立ったのは、2025/12/20のことでした。": [.japanese: "PM5と接続し、屋外だけでなく屋内での記録ができるようにすると思い立ったのは、2025/12/20のことでした。", .english: "PM5と接続し、屋外だけでなく屋内での記録ができるようにすると思い立ったのは、2025/12/20のことでした。"],
        "PM5にデータ送信成功": [.japanese: "PM5にデータ送信成功", .english: "PM5にデータ送信成功"],
        "PM5のカスタムネームや表示上の並び替えができます。ダッシュボードやレースビュー時に便利な機能です。": [.japanese: "PM5のカスタムネームや表示上の並び替えができます。ダッシュボードやレースビュー時に便利な機能です。", .english: "PM5のカスタムネームや表示上の並び替えができます。ダッシュボードやレースビュー時に便利な機能です。"],
        "PM5の名前/順番の変更が可能に。": [.japanese: "PM5の名前/順番の変更が可能に。", .english: "PM5の名前/順番の変更が可能に。"],
        "PM5の設定->ファームウェアバージョンを確認してください。": [.japanese: "PM5の設定->ファームウェアバージョンを確認してください。", .english: "PM5の設定->ファームウェアバージョンを確認してください。"],
        "PM5デバイス一覧": [.japanese: "PM5デバイス一覧", .english: "PM5デバイス一覧"],
        "PM5側でConnectボタンを押し、アプリの画面に表示されたPM5 ID（例: 430665873）と合致するものを選択します。": [.japanese: "PM5側でConnectボタンを押し、アプリの画面に表示されたPM5 ID（例: 430665873）と合致するものを選択します。", .english: "PM5側でConnectボタンを押し、アプリの画面に表示されたPM5 ID（例: 430665873）と合致するものを選択します。"],
        "PM5編集": [.japanese: "PM5編集", .english: "PM5編集"],
        "PM5複数台同時接続機能に加え、最大1名のメンバーにプランを共有できます。チーム全員でデータを共有し、練習の効率化と記録管理を一元化できます。": [.japanese: "PM5複数台同時接続機能に加え、最大1名のメンバーにプランを共有できます。チーム全員でデータを共有し、練習の効率化と記録管理を一元化できます。", .english: "In addition to the multi-device connection feature for PM5, you can share the plan with up to 1 member. The whole team can share data, streamline practice, and centralize record management."],
        "Pitch (Side View)": [.japanese: "Pitch (Side View)", .english: "Pitch (Side View)"],
        "Pro,Manager,Team,MAXの課金プランを追加": [.japanese: "Pro,Manager,Team,MAXの課金プランを追加", .english: "Pro,Manager,Team,MAXの課金プランを追加"],
        "Profile Info": [.japanese: "Profile Info", .english: "Profile Info"],
        "QAコーナーに移る": [.japanese: "QAコーナーに移る", .english: "QAコーナーに移る"],
        "Resetting...": [.japanese: "Resetting...", .english: "Resetting..."],
        "Rest: ": [.japanese: "Rest: ", .english: "Rest: "],
        "Results Saved": [.japanese: "Results Saved", .english: "Results Saved"],
        "RowModeの横向き制御機構を更新": [.japanese: "RowModeの横向き制御機構を更新", .english: "RowModeの横向き制御機構を更新"],
        "RowPilot プランを選ぶ": [.japanese: "RowPilot プランを選ぶ", .english: "RowPilot プランを選ぶ"],
        "RowPilotの中核となる基本的な機能を使用できます。潮汐情報の確認やGPSレート計、PM5との1:1接続など、日常のトレーニングに必要な機能を揃えています。": [.japanese: "RowPilotの中核となる基本的な機能を使用できます。潮汐情報の確認やGPSレート計、PM5との1:1接続など、日常のトレーニングに必要な機能を揃えています。", .english: "RowPilotの中核となる基本的な機能を使用できます。潮汐情報の確認やGPSレート計、PM5との1:1接続など、日常のトレーニングに必要な機能を揃えています。"],
        "RowPilotの基本機能やPM5との通信方法についてのガイドです。": [.japanese: "RowPilotの基本機能やPM5との通信方法についてのガイドです。", .english: "RowPilotの基本機能やPM5との通信方法についてのガイドです。"],
        "RowPilotの生まれた背景": [.japanese: "RowPilotの生まれた背景", .english: "RowPilotの生まれた背景"],
        "RowPilotは、ボート競技における情報の非対称性をなくし、": [.japanese: "RowPilotは、ボート競技における情報の非対称性をなくし、", .english: "RowPilotは、ボート競技における情報の非対称性をなくし、"],
        "RowPilotは、部活で使用するGPSレート計が不足していることを解決するために開発が始まりました。": [.japanese: "RowPilotは、部活で使用するGPSレート計が不足していることを解決するために開発が始まりました。", .english: "RowPilotは、部活で使用するGPSレート計が不足していることを解決するために開発が始まりました。"],
        "RowPilotは誕生しました。": [.japanese: "RowPilotは誕生しました。", .english: "RowPilotは誕生しました。"],
        "RowPilotを支えてくれた人々": [.japanese: "RowPilotを支えてくれた人々", .english: "RowPilotを支えてくれた人々"],
        "RowPilot内の文字を英語に変更できるように": [.japanese: "RowPilot内の文字を英語に変更できるように", .english: "RowPilot内の文字を英語に変更できるように"],
        "SOS機能の大幅追加": [.japanese: "SOS機能の大幅追加", .english: "SOS機能の大幅追加"],
        "SOS機能の追加・利用規約の作成": [.japanese: "SOS機能の追加・利用規約の作成", .english: "SOS機能の追加・利用規約の作成"],
        "Save Workout": [.japanese: "Save Workout", .english: "Save Workout"],
        "Scan PM5": [.japanese: "Scan PM5", .english: "Scan PM5"],
        "Seat": [.japanese: "Seat", .english: "Seat"],
        "Span": [.japanese: "Span", .english: "Span"],
        "Split Calories": [.japanese: "Split Calories", .english: "Split Calories"],
        "Split Distance": [.japanese: "Split Distance", .english: "Split Distance"],
        "Split Time": [.japanese: "Split Time", .english: "Split Time"],
        "SplitMeterの指定が可能に": [.japanese: "SplitMeterの指定が可能に", .english: "SplitMeterの指定が可能に"],
        "Spread": [.japanese: "Spread", .english: "Spread"],
        "Start rowing to see force curve": [.japanese: "Start rowing to see force curve", .english: "Start rowing to see force curve"],
        "Strava同期 (準備中)": [.japanese: "Strava同期 (準備中)", .english: "Strava同期 (準備中)"],
        "S先生": [.japanese: "S先生", .english: "S先生"],
        "Tap to configure boat & oars": [.japanese: "Tap to configure boat & oars", .english: "Tap to configure boat & oars"],
        "Team / MAXユーザーから共有された8文字のコード": [.japanese: "Team / MAXユーザーから共有された8文字のコード", .english: "Team / MAXユーザーから共有された8文字のコード"],
        "Team Join": [.japanese: "Team Join", .english: "Team Join"],
        "Team Management": [.japanese: "Team Management", .english: "Team Management"],
        "Team/MAXユーザーから招待コードをもらう": [.japanese: "Team/MAXユーザーから招待コードをもらう", .english: "Team/MAXユーザーから招待コードをもらう"],
        "Team/MAXユーザーのコードを入力してManagerプランを利用": [.japanese: "Team/MAXユーザーのコードを入力してManagerプランを利用", .english: "Team/MAXユーザーのコードを入力してManagerプランを利用"],
        "TideViewの横向き対応": [.japanese: "TideViewの横向き対応", .english: "TideViewの横向き対応"],
        "Variable Interval Communication Architecture v1の作成": [.japanese: "Variable Interval Communication Architecture v1の作成", .english: "Variable Interval Communication Architecture v1の作成"],
        "Workout Menu": [.japanese: "Workout Menu", .english: "Workout Menu"],
        "Would you like to save this workout as an indoor workout?": [.japanese: "Would you like to save this workout as an indoor workout?", .english: "Would you like to save this workout as an indoor workout?"],
        "You": [.japanese: "You", .english: "You"],
        "iPad版ではRowModeを使用できません": [.japanese: "iPad版ではRowModeを使用できません", .english: "iPad版ではRowModeを使用できません"],
        "iPhoneを艇に装着して使用してください": [.japanese: "iPhoneを艇に装着して使用してください", .english: "iPhoneを艇に装着して使用してください"],
        "redditのユーザー": [.japanese: "redditのユーザー", .english: "redditのユーザー"],
        "s/m": [.japanese: "s/m", .english: "s/m"],
        "※ Manager Plan共有コードとは別のコードです": [.japanese: "※ Manager Plan共有コードとは別のコードです", .english: "※ Manager Plan共有コードとは別のコードです"],
        "※これを利用するにはRowPilot Managerのサブスクリプション登録が必要です。": [.japanese: "※これを利用するにはRowPilot Managerのサブスクリプション登録が必要です。", .english: "※これを利用するにはRowPilot Managerのサブスクリプション登録が必要です。"],
        "ℹ️ Manager Plan共有との違い": [.japanese: "ℹ️ Manager Plan共有との違い", .english: "ℹ️ Manager Plan共有との違い"],
        "⚠️ 申請する前に、上のフィールドに表示名を入力してください。この名前がオーナーに表示されます。": [.japanese: "⚠️ 申請する前に、上のフィールドに表示名を入力してください。この名前がオーナーに表示されます。", .english: "⚠️ 申請する前に、上のフィールドに表示名を入力してください。この名前がオーナーに表示されます。"],
        "⚠️ 申請する前に、上のフィールドに表示名を入力してください。この名前が顧問に表示されます。": [.japanese: "⚠️ 申請する前に、上のフィールドに表示名を入力してください。この名前が顧問に表示されます。", .english: "⚠️ 申請する前に、上のフィールドに表示名を入力してください。この名前が顧問に表示されます。"],
        "「PM5をスキャン」を押します。": [.japanese: "「PM5をスキャン」を押します。", .english: "「PM5をスキャン」を押します。"],
        "「PM5設定」ボタン": [.japanese: "「PM5設定」ボタン", .english: "「PM5設定」ボタン"],
        "「もう一度」ボタン": [.japanese: "「もう一度」ボタン", .english: "「もう一度」ボタン"],
        "「次へ→」を選択し、単一距離か単一時間ワークアウトを設定します。対応レンジ内で距離・時間を設定し送信します(送信台数に応じて少し時間がかかります)。": [.japanese: "「次へ→」を選択し、単一距離か単一時間ワークアウトを設定します。対応レンジ内で距離・時間を設定し送信します(送信台数に応じて少し時間がかかります)。", .english: "「次へ→」を選択し、単一距離か単一時間ワークアウトを設定します。対応レンジ内で距離・時間を設定し送信します(送信台数に応じて少し時間がかかります)。"],
        "「設定」ボタン": [.japanese: "「設定」ボタン", .english: "「設定」ボタン"],
        "あなたのトレーニングを、次のステージへ。": [.japanese: "あなたのトレーニングを、次のステージへ。", .english: "あなたのトレーニングを、次のステージへ。"],
        "こうして、": [.japanese: "こうして、", .english: "こうして、"],
        "こうして皆さんの支えがあって、": [.japanese: "こうして皆さんの支えがあって、", .english: "こうして皆さんの支えがあって、"],
        "このアプリが完成するまでには、本当にたくさんの人が関わってくれました。": [.japanese: "このアプリが完成するまでには、本当にたくさんの人が関わってくれました。", .english: "このアプリが完成するまでには、本当にたくさんの人が関わってくれました。"],
        "このアプリの開発には約1年かかっています。手を動かした時間だけでも、ゆうに半年を超えます。": [.japanese: "このアプリの開発には約1年かかっています。手を動かした時間だけでも、ゆうに半年を超えます。", .english: "このアプリの開発には約1年かかっています。手を動かした時間だけでも、ゆうに半年を超えます。"],
        "このアプリは、たまたまパソコンがある環境だけを持ち合わせた、プログラミングについてはほとんど知らない高校生が、AIとともに興味と好奇心だけで作り上げたものです。": [.japanese: "このアプリは、たまたまパソコンがある環境だけを持ち合わせた、プログラミングについてはほとんど知らない高校生が、AIとともに興味と好奇心だけで作り上げたものです。", .english: "このアプリは、たまたまパソコンがある環境だけを持ち合わせた、プログラミングについてはほとんど知らない高校生が、AIとともに興味と好奇心だけで作り上げたものです。"],
        "このアプリは完成しました。": [.japanese: "このアプリは完成しました。", .english: "このアプリは完成しました。"],
        "このコードをチームメンバーに共有してください。\nメンバーが入力するとチーム参加申請が届きます。": [.japanese: "このコードをチームメンバーに共有してください。\nメンバーが入力するとチーム参加申請が届きます。", .english: "このコードをチームメンバーに共有してください。\nメンバーが入力するとチーム参加申請が届きます。"],
        "このコードをチームメンバーに共有してください。\nメンバーが入力すると共有申請が届きます。": [.japanese: "このコードをチームメンバーに共有してください。\nメンバーが入力すると共有申請が届きます。", .english: "このコードをチームメンバーに共有してください。\nメンバーが入力すると共有申請が届きます。"],
        "この名前がオーナーに表示されます。": [.japanese: "この名前がオーナーに表示されます。", .english: "この名前がオーナーに表示されます。"],
        "この名前が顧問に表示されます。": [.japanese: "この名前が顧問に表示されます。", .english: "この名前が顧問に表示されます。"],
        "これほどの長期間、モチベーションなしに動き続けるのは、ごく一部の人間でない限り不可能です。": [.japanese: "これほどの長期間、モチベーションなしに動き続けるのは、ごく一部の人間でない限り不可能です。", .english: "これほどの長期間、モチベーションなしに動き続けるのは、ごく一部の人間でない限り不可能です。"],
        "さらに、顧問の先生に頼めばローエルゴを長期間貸してもらえたり、海外のConcept2のエンジニアにメールすると丁寧に返信・解説してもらえたりと、これ以上ないほど恵まれた環境にいます。": [.japanese: "さらに、顧問の先生に頼めばローエルゴを長期間貸してもらえたり、海外のConcept2のエンジニアにメールすると丁寧に返信・解説してもらえたりと、これ以上ないほど恵まれた環境にいます。", .english: "さらに、顧問の先生に頼めばローエルゴを長期間貸してもらえたり、海外のConcept2のエンジニアにメールすると丁寧に返信・解説してもらえたりと、これ以上ないほど恵まれた環境にいます。"],
        "しかし、BluetoothでPM5と接続することは容易ではありませんでした。": [.japanese: "しかし、BluetoothでPM5と接続することは容易ではありませんでした。", .english: "しかし、BluetoothでPM5と接続することは容易ではありませんでした。"],
        "しかし、環境があるだけではこのアプリは生まれませんでした。": [.japanese: "しかし、環境があるだけではこのアプリは生まれませんでした。", .english: "しかし、環境があるだけではこのアプリは生まれませんでした。"],
        "すると、驚くべきことに": [.japanese: "すると、驚くべきことに", .english: "すると、驚くべきことに"],
        "そうしてRowPilotは、単なる計測アプリではなくなっていきました。": [.japanese: "そうしてRowPilotは、単なる計測アプリではなくなっていきました。", .english: "そうしてRowPilotは、単なる計測アプリではなくなっていきました。"],
        "そうして、2/12に初めてPM5にトレーニングメニューを送ることができ、": [.japanese: "そうして、2/12に初めてPM5にトレーニングメニューを送ることができ、", .english: "そうして、2/12に初めてPM5にトレーニングメニューを送ることができ、"],
        "そうして続けることで、誰かの役に立つ新しい仕組みや、今までになかったアイデアが生まれるはずです。": [.japanese: "そうして続けることで、誰かの役に立つ新しい仕組みや、今までになかったアイデアが生まれるはずです。", .english: "そうして続けることで、誰かの役に立つ新しい仕組みや、今までになかったアイデアが生まれるはずです。"],
        "そこで、各クルーが持っているスマートフォンを使って": [.japanese: "そこで、各クルーが持っているスマートフォンを使って", .english: "そこで、各クルーが持っているスマートフォンを使って"],
        "そして、": [.japanese: "そして、", .english: "そして、"],
        "そして、その「何か」をどうか大切にしてください。": [.japanese: "そして、その「何か」をどうか大切にしてください。", .english: "そして、その「何か」をどうか大切にしてください。"],
        "そして、データ取得の際に手助けをしてくれた、": [.japanese: "そして、データ取得の際に手助けをしてくれた、", .english: "そして、データ取得の際に手助けをしてくれた、"],
        "そして仮にこのような環境になかったとしても、ローイング関連の部活に入り、技術マネージャーという立場を経験していれば、規模は違えど似たようなアプリは作っていたと思います。": [.japanese: "そして仮にこのような環境になかったとしても、ローイング関連の部活に入り、技術マネージャーという立場を経験していれば、規模は違えど似たようなアプリは作っていたと思います。", .english: "そして仮にこのような環境になかったとしても、ローイング関連の部活に入り、技術マネージャーという立場を経験していれば、規模は違えど似たようなアプリは作っていたと思います。"],
        "その他の機能（Practice, Tide等）は\niPadでもご利用いただけます": [.japanese: "その他の機能（Practice, Tide等）は\niPadでもご利用いただけます", .english: "その他の機能（Practice, Tide等）は\niPadでもご利用いただけます"],
        "それから1ヶ月後には、9台のPM5に同時にトレーニングメニューを送信し、": [.japanese: "それから1ヶ月後には、9台のPM5に同時にトレーニングメニューを送信し、", .english: "それから1ヶ月後には、9台のPM5に同時にトレーニングメニューを送信し、"],
        "それでも解決しない場合はConcept2に連絡してください。": [.japanese: "それでも解決しない場合はConcept2に連絡してください。", .english: "それでも解決しない場合はConcept2に連絡してください。"],
        "そんな時は、成功した時の情景を強くイメージしてみてください。きっとそこに向かうモチベーションが湧いてきます。": [.japanese: "そんな時は、成功した時の情景を強くイメージしてみてください。きっとそこに向かうモチベーションが湧いてきます。", .english: "そんな時は、成功した時の情景を強くイメージしてみてください。きっとそこに向かうモチベーションが湧いてきます。"],
        "はい、許可する": [.japanese: "はい、許可する", .english: "はい、許可する"],
        "まず、PM5との通信について全くわからない時から支えてくださった": [.japanese: "まず、PM5との通信について全くわからない時から支えてくださった", .english: "まず、PM5との通信について全くわからない時から支えてくださった"],
        "まずは基本機能から": [.japanese: "まずは基本機能から", .english: "まずは基本機能から"],
        "また、UI面でも苦労しました。": [.japanese: "また、UI面でも苦労しました。", .english: "また、UI面でも苦労しました。"],
        "また、改善案を出してくれた": [.japanese: "また、改善案を出してくれた", .english: "また、改善案を出してくれた"],
        "もう一度": [.japanese: "もう一度", .english: "もう一度"],
        "もう一度 (ロック中)": [.japanese: "もう一度 (ロック中)", .english: "もう一度 (ロック中)"],
        "もちろんしんどいこともあります。": [.japanese: "もちろんしんどいこともあります。", .english: "もちろんしんどいこともあります。"],
        "より多くの人が使いやすいように工夫しました。": [.japanese: "より多くの人が使いやすいように工夫しました。", .english: "より多くの人が使いやすいように工夫しました。"],
        "アップデート情報": [.japanese: "アップデート情報", .english: "アップデート情報"],
        "インポート": [.japanese: "インポート", .english: "インポート"],
        "エラー": [.japanese: "エラー", .english: "エラー"],
        "オーナーが承認すると自動でManagerプランが適用される": [.japanese: "オーナーが承認すると自動でManagerプランが適用される", .english: "オーナーが承認すると自動でManagerプランが適用される"],
        "カードの表示サイズ": [.japanese: "カードの表示サイズ", .english: "カードの表示サイズ"],
        "キャンセル": [.japanese: "キャンセル", .english: "キャンセル"],
        "キャンセル後も有効期限まで利用できます。": [.japanese: "キャンセル後も有効期限まで利用できます。", .english: "キャンセル後も有効期限まで利用できます。"],
        "クルーメンバーを記録": [.japanese: "クルーメンバーを記録", .english: "クルーメンバーを記録"],
        "クルー名": [.japanese: "クルー名", .english: "クルー名"],
        "クルー情報を削除": [.japanese: "クルー情報を削除", .english: "クルー情報を削除"],
        "クルー編集": [.japanese: "クルー編集", .english: "クルー編集"],
        "コックス": [.japanese: "コックス", .english: "コックス"],
        "コードを入力して「チーム参加を申請する」をタップ": [.japanese: "コードを入力して「チーム参加を申請する」をタップ", .english: "コードを入力して「チーム参加を申請する」をタップ"],
        "コードを入力して「共有を申請する」をタップ": [.japanese: "コードを入力して「共有を申請する」をタップ", .english: "コードを入力して「共有を申請する」をタップ"],
        "サマリー情報": [.japanese: "サマリー情報", .english: "サマリー情報"],
        "タグ": [.japanese: "タグ", .english: "タグ"],
        "ダッシュボード画面にてスマホを横倒しにするとレースをしているような見た目に変更することができます。2000mTTや練習でレース練習をする際におすすめです。": [.japanese: "ダッシュボード画面にてスマホを横倒しにするとレースをしているような見た目に変更することができます。2000mTTや練習でレース練習をする際におすすめです。", .english: "ダッシュボード画面にてスマホを横倒しにするとレースをしているような見た目に変更することができます。2000mTTや練習でレース練習をする際におすすめです。"],
        "チームに参加する": [.japanese: "チームに参加する", .english: "チームに参加する"],
        "チームのTeam / MAXユーザーから発行された\n招待コードを入力してください": [.japanese: "チームのTeam / MAXユーザーから発行された\n招待コードを入力してください", .english: "チームのTeam / MAXユーザーから発行された\n招待コードを入力してください"],
        "チームへの参加を申請しています": [.japanese: "チームへの参加を申請しています", .english: "チームへの参加を申請しています"],
        "チームへの参加申請を管理し、練習記録を確認します。": [.japanese: "チームへの参加申請を管理し、練習記録を確認します。", .english: "チームへの参加申請を管理し、練習記録を確認します。"],
        "チームメンバー": [.japanese: "チームメンバー", .english: "チームメンバー"],
        "チームメンバーはまだいません": [.japanese: "チームメンバーはまだいません", .english: "チームメンバーはまだいません"],
        "チーム全体で高め合える文化を広げていきたいと考えています。": [.japanese: "チーム全体で高め合える文化を広げていきたいと考えています。", .english: "チーム全体で高め合える文化を広げていきたいと考えています。"],
        "チーム全員で使える": [.japanese: "チーム全員で使える", .english: "チーム全員で使える"],
        "チーム参加はManagerプランの共有とは異なります。チーム参加では、あなたの練習記録が顧問の端末に配信されます。Managerプランの機能が共有されるわけではありません。": [.japanese: "チーム参加はManagerプランの共有とは異なります。チーム参加では、あなたの練習記録が顧問の端末に配信されます。Managerプランの機能が共有されるわけではありません。", .english: "チーム参加はManagerプランの共有とは異なります。チーム参加では、あなたの練習記録が顧問の端末に配信されます。Managerプランの機能が共有されるわけではありません。"],
        "チーム参加を申請する": [.japanese: "チーム参加を申請する", .english: "チーム参加を申請する"],
        "チーム参加申請": [.japanese: "チーム参加申請", .english: "チーム参加申請"],
        "チーム招待コード": [.japanese: "チーム招待コード", .english: "チーム招待コード"],
        "チーム招待コードをリセットすると、現在の全チームメンバーが削除されます。\nこの操作は取り消せません。\n\n※ リセットは1週間に1回のみ可能です。": [.japanese: "チーム招待コードをリセットすると、現在の全チームメンバーが削除されます。\nこの操作は取り消せません。\n\n※ リセットは1週間に1回のみ可能です。", .english: "チーム招待コードをリセットすると、現在の全チームメンバーが削除されます。\nこの操作は取り消せません。\n\n※ リセットは1週間に1回のみ可能です。"],
        "チーム招待コードを入力": [.japanese: "チーム招待コードを入力", .english: "チーム招待コードを入力"],
        "チーム管理": [.japanese: "チーム管理", .english: "チーム管理"],
        "データ取得スピード (Hz)": [.japanese: "データ取得スピード (Hz)", .english: "データ取得スピード (Hz)"],
        "データ送信中のUIを変更": [.japanese: "データ送信中のUIを変更", .english: "データ送信中のUIを変更"],
        "ドラッグで並び替え、テキストをタップして名前を変更できます。名前を空にするとBLE名に戻ります。": [.japanese: "ドラッグで並び替え、テキストをタップして名前を変更できます。名前を空にするとBLE名に戻ります。", .english: "ドラッグで並び替え、テキストをタップして名前を変更できます。名前を空にするとBLE名に戻ります。"],
        "ネットワーク接続を確認して\nもう一度お試しください": [.japanese: "ネットワーク接続を確認して\nもう一度お試しください", .english: "ネットワーク接続を確認して\nもう一度お試しください"],
        "バックアップから復元。": [.japanese: "バックアップから復元。", .english: "バックアップから復元。"],
        "バージョン178以前では恐らく動作しません。": [.japanese: "バージョン178以前では恐らく動作しません。", .english: "バージョン178以前では恐らく動作しません。"],
        "バージョン履歴": [.japanese: "バージョン履歴", .english: "バージョン履歴"],
        "パフォーマンス": [.japanese: "パフォーマンス", .english: "パフォーマンス"],
        "プランについて": [.japanese: "プランについて", .english: "プランについて"],
        "プランの共有 (最大1名)": [.japanese: "プランの共有 (最大1名)", .english: "Plan sharing (up to 1 member)"],
        "プランの共有 (最大3名)": [.japanese: "プランの共有 (最大3名)", .english: "Plan sharing (up to 3 members)"],
        "プレビュー": [.japanese: "プレビュー", .english: "プレビュー"],
        "プロコーチのための最高峰": [.japanese: "プロコーチのための最高峰", .english: "プロコーチのための最高峰"],
        "ペース:": [.japanese: "ペース:", .english: "ペース:"],
        "ペースメーカー設定": [.japanese: "ペースメーカー設定", .english: "ペースメーカー設定"],
        "ペース入力": [.japanese: "ペース入力", .english: "ペース入力"],
        "ボート部だけでなくローイングに関わるすべての人が使いやすいアプリを目指して": [.japanese: "ボート部だけでなくローイングに関わるすべての人が使いやすいアプリを目指して", .english: "ボート部だけでなくローイングに関わるすべての人が使いやすいアプリを目指して"],
        "ボート部の先輩方や友人たち。": [.japanese: "ボート部の先輩方や友人たち。", .english: "ボート部の先輩方や友人たち。"],
        "ボート部員たち。": [.japanese: "ボート部員たち。", .english: "ボート部員たち。"],
        "ボート部員全員が使いやすいアプリにしたいと考え直し、": [.japanese: "ボート部員全員が使いやすいアプリにしたいと考え直し、", .english: "ボート部員全員が使いやすいアプリにしたいと考え直し、"],
        "マネージャーモード(複数台通信機能)の追加": [.japanese: "マネージャーモード(複数台通信機能)の追加", .english: "マネージャーモード(複数台通信機能)の追加"],
        "マネージャーモードにおける通信の不安定さを低減": [.japanese: "マネージャーモードにおける通信の不安定さを低減", .english: "マネージャーモードにおける通信の不安定さを低減"],
        "マネージャーモードにおける通信アーキテクチャを規定化し刷新": [.japanese: "マネージャーモードにおける通信アーキテクチャを規定化し刷新", .english: "マネージャーモードにおける通信アーキテクチャを規定化し刷新"],
        "マネージャーモードのUI追加": [.japanese: "マネージャーモードのUI追加", .english: "マネージャーモードのUI追加"],
        "マネージャーモードを選択後、PM5をスキャンします。": [.japanese: "マネージャーモードを選択後、PM5をスキャンします。", .english: "マネージャーモードを選択後、PM5をスキャンします。"],
        "メモ": [.japanese: "メモ", .english: "メモ"],
        "メンバーが練習を記録すると\n自動的にここに表示されます": [.japanese: "メンバーが練習を記録すると\n自動的にここに表示されます", .english: "メンバーが練習を記録すると\n自動的にここに表示されます"],
        "メンバーの練習記録をリアルタイムで管理": [.japanese: "メンバーの練習記録をリアルタイムで管理", .english: "メンバーの練習記録をリアルタイムで管理"],
        "メンバーの記録": [.japanese: "メンバーの記録", .english: "メンバーの記録"],
        "メンバーの記録はまだありません": [.japanese: "メンバーの記録はまだありません", .english: "メンバーの記録はまだありません"],
        "メンバーを管理": [.japanese: "メンバーを管理", .english: "メンバーを管理"],
        "メートル": [.japanese: "メートル", .english: "メートル"],
        "リギングの管理": [.japanese: "リギングの管理", .english: "リギングの管理"],
        "リセット": [.japanese: "リセット", .english: "リセット"],
        "リセット時は全メンバーが削除されます • 1週間に1回のみ": [.japanese: "リセット時は全メンバーが削除されます • 1週間に1回のみ", .english: "リセット時は全メンバーが削除されます • 1週間に1回のみ"],
        "レースズーム": [.japanese: "レースズーム", .english: "レースズーム"],
        "レースズーム設定": [.japanese: "レースズーム設定", .english: "レースズーム設定"],
        "レースビュー (MAXのみ)": [.japanese: "レースビュー (MAXのみ)", .english: "レースビュー (MAXのみ)"],
        "レースビュー (高度な可視化)": [.japanese: "レースビュー (高度な可視化)", .english: "レースビュー (高度な可視化)"],
        "レースビューにおけるレーン固定やペースメーカーの追加": [.japanese: "レースビューにおけるレーン固定やペースメーカーの追加", .english: "レースビューにおけるレーン固定やペースメーカーの追加"],
        "レースビューの変更": [.japanese: "レースビューの変更", .english: "レースビューの変更"],
        "レースビューの追加。": [.japanese: "レースビューの追加。", .english: "レースビューの追加。"],
        "レーン固定": [.japanese: "レーン固定", .english: "レーン固定"],
        "ワット・予測時間・HRはデータが利用可能な場合のみ表示されます": [.japanese: "ワット・予測時間・HRはデータが利用可能な場合のみ表示されます", .english: "ワット・予測時間・HRはデータが利用可能な場合のみ表示されます"],
        "ワークアウトの内容を変更": [.japanese: "ワークアウトの内容を変更", .english: "ワークアウトの内容を変更"],
        "ワークアウトの再設定や取得スピード（Hz）の設定変更ができます。強制的にPM5のワークアウト設定がリセットされるのでワークアウト中に操作しないようにしてください。": [.japanese: "ワークアウトの再設定や取得スピード（Hz）の設定変更ができます。強制的にPM5のワークアウト設定がリセットされるのでワークアウト中に操作しないようにしてください。", .english: "ワークアウトの再設定や取得スピード（Hz）の設定変更ができます。強制的にPM5のワークアウト設定がリセットされるのでワークアウト中に操作しないようにしてください。"],
        "ワークアウト変更": [.japanese: "ワークアウト変更", .english: "ワークアウト変更"],
        "ワークアウト詳細グラフ": [.japanese: "ワークアウト詳細グラフ", .english: "ワークアウト詳細グラフ"],
        "一人ひとりの努力が可視化され、": [.japanese: "一人ひとりの努力が可視化され、", .english: "一人ひとりの努力が可視化され、"],
        "一度接続を切って確認してください。": [.japanese: "一度接続を切って確認してください。", .english: "一度接続を切って確認してください。"],
        "不変・可変インタビュー機能を追加": [.japanese: "不変・可変インタビュー機能を追加", .english: "不変・可変インタビュー機能を追加"],
        "中": [.japanese: "中", .english: "中"],
        "以下の環境で8台同時のテストを行なっていますが動作にラグは生じていません。参考程度に。": [.japanese: "以下の環境で8台同時のテストを行なっていますが動作にラグは生じていません。参考程度に。", .english: "以下の環境で8台同時のテストを行なっていますが動作にラグは生じていません。参考程度に。"],
        "任意の距離・時間を指定して送信できるように": [.japanese: "任意の距離・時間を指定して送信できるように", .english: "任意の距離・時間を指定して送信できるように"],
        "使用する全てのPM5を接続可能状態にし、使用するPM5の全てを追加します。": [.japanese: "使用する全てのPM5を接続可能状態にし、使用するPM5の全てを追加します。", .english: "使用する全てのPM5を接続可能状態にし、使用するPM5の全てを追加します。"],
        "僕が伝えたいことは、「興味を持ったことは、何でもやり続けてほしい」ということです。": [.japanese: "僕が伝えたいことは、「興味を持ったことは、何でもやり続けてほしい」ということです。", .english: "僕が伝えたいことは、「興味を持ったことは、何でもやり続けてほしい」ということです。"],
        "僕は幸いにも恵まれた環境にいます。手元にはPCがあり、AIが急速に発展してきた時代のど真ん中で生きています。": [.japanese: "僕は幸いにも恵まれた環境にいます。手元にはPCがあり、AIが急速に発展してきた時代のど真ん中で生きています。", .english: "僕は幸いにも恵まれた環境にいます。手元にはPCがあり、AIが急速に発展してきた時代のど真ん中で生きています。"],
        "共有を申請する": [.japanese: "共有を申請する", .english: "共有を申請する"],
        "共有プラン": [.japanese: "共有プラン", .english: "共有プラン"],
        "共有メンバーを管理": [.japanese: "共有メンバーを管理", .english: "共有メンバーを管理"],
        "共有中のメンバーはいません": [.japanese: "共有中のメンバーはいません", .english: "共有中のメンバーはいません"],
        "再試行": [.japanese: "再試行", .english: "再試行"],
        "利用中": [.japanese: "利用中", .english: "利用中"],
        "削除": [.japanese: "削除", .english: "削除"],
        "削除する": [.japanese: "削除する", .english: "削除する"],
        "動作確認環境:iPhone12, iOS26.2 / iPhone17,iOS26.5 / iPad Pro M1,iPadOS26.5": [.japanese: "動作確認環境:iPhone12, iOS26.2 / iPhone17,iOS26.5 / iPad Pro M1,iPadOS26.5", .english: "動作確認環境:iPhone12, iOS26.2 / iPhone17,iOS26.5 / iPad Pro M1,iPadOS26.5"],
        "動作確認環境:v178.037 / PM5のみ": [.japanese: "動作確認環境:v178.037 / PM5のみ", .english: "動作確認環境:v178.037 / PM5のみ"],
        "半ば諦めかけていたところ、本社の方にメールをすることにしました。": [.japanese: "半ば諦めかけていたところ、本社の方にメールをすることにしました。", .english: "半ば諦めかけていたところ、本社の方にメールをすることにしました。"],
        "参加の流れ": [.japanese: "参加の流れ", .english: "参加の流れ"],
        "取得頻度:": [.japanese: "取得頻度:", .english: "取得頻度:"],
        "受信したワークアウトデータをインポートしますか？": [.japanese: "受信したワークアウトデータをインポートしますか？", .english: "受信したワークアウトデータをインポートしますか？"],
        "各機能の解説": [.japanese: "各機能の解説", .english: "各機能の解説"],
        "含まれる機能": [.japanese: "含まれる機能", .english: "含まれる機能"],
        "大": [.japanese: "大", .english: "大"],
        "学校の部活動には十分な台数がなく、高価なので艇の人数分を用意することは難しいのが課題でした。": [.japanese: "学校の部活動には十分な台数がなく、高価なので艇の人数分を用意することは難しいのが課題でした。", .english: "学校の部活動には十分な台数がなく、高価なので艇の人数分を用意することは難しいのが課題でした。"],
        "完了": [.japanese: "完了", .english: "完了"],
        "実際にこのアプリの成長を願い、ローエルゴを貸してくださった": [.japanese: "実際にこのアプリの成長を願い、ローエルゴを貸してくださった", .english: "実際にこのアプリの成長を願い、ローエルゴを貸してくださった"],
        "小": [.japanese: "小", .english: "小"],
        "当初はシンプルなデザインを考えていたのですが、": [.japanese: "当初はシンプルなデザインを考えていたのですが、", .english: "当初はシンプルなデザインを考えていたのですが、"],
        "承認する": [.japanese: "承認する", .english: "承認する"],
        "承認待ちの申請": [.japanese: "承認待ちの申請", .english: "承認待ちの申請"],
        "技術的な挑戦": [.japanese: "技術的な挑戦", .english: "技術的な挑戦"],
        "拒否": [.japanese: "拒否", .english: "拒否"],
        "拒否する": [.japanese: "拒否する", .english: "拒否する"],
        "招待コード": [.japanese: "招待コード", .english: "招待コード"],
        "招待コードで申請": [.japanese: "招待コードで申請", .english: "招待コードで申請"],
        "招待コードをメンバーに共有して\n申請を承認するとここに表示されます": [.japanese: "招待コードをメンバーに共有して\n申請を承認するとここに表示されます", .english: "招待コードをメンバーに共有して\n申請を承認するとここに表示されます"],
        "招待コードをリセットすると、現在共有中の全メンバーが削除され、共有が停止されます。\nこの操作は取り消せません。\n\n※ リセットは1週間に1回のみ可能です。": [.japanese: "招待コードをリセットすると、現在共有中の全メンバーが削除され、共有が停止されます。\nこの操作は取り消せません。\n\n※ リセットは1週間に1回のみ可能です。", .english: "招待コードをリセットすると、現在共有中の全メンバーが削除され、共有が停止されます。\nこの操作は取り消せません。\n\n※ リセットは1週間に1回のみ可能です。"],
        "招待コードを入力": [.japanese: "招待コードを入力", .english: "招待コードを入力"],
        "接続しているPM5の数が多くなる/受信頻度を上げるほど動作に影響が出る可能性があります。": [.japanese: "接続しているPM5の数が多くなる/受信頻度を上げるほど動作に影響が出る可能性があります。", .english: "接続しているPM5の数が多くなる/受信頻度を上げるほど動作に影響が出る可能性があります。"],
        "操作しやすいレイアウトを心がけたりと、": [.japanese: "操作しやすいレイアウトを心がけたりと、", .english: "操作しやすいレイアウトを心がけたりと、"],
        "文字通り最初に設定したワークアウトを繰り返すことができます。押すとワークアウトを保存・破棄を選択し、自動的にPM5のリセット->ワークアウトの設定が完了します。": [.japanese: "文字通り最初に設定したワークアウトを繰り返すことができます。押すとワークアウトを保存・破棄を選択し、自動的にPM5のリセット->ワークアウトの設定が完了します。", .english: "文字通り最初に設定したワークアウトを繰り返すことができます。押すとワークアウトを保存・破棄を選択し、自動的にPM5のリセット->ワークアウトの設定が完了します。"],
        "時間": [.japanese: "時間", .english: "時間"],
        "時間:": [.japanese: "時間:", .english: "時間:"],
        "最大3名のメンバーへのプラン共有に加え、CSV形式での記録出力や高度なレースビュー、グラフィカルなアナリティクスを開放します。プロコーチ・エリートチームのためのプランです。": [.japanese: "最大3名のメンバーへのプラン共有に加え、CSV形式での記録出力や高度なレースビュー、グラフィカルなアナリティクスを開放します。プロコーチ・エリートチームのためのプランです。", .english: "In addition to plan sharing for up to 3 members, CSV export, advanced Race View, and graphical analytics are unlocked. This plan is designed for professional coaches and elite teams."],
        "最大同時接続数は10台までにしていますが、使用者の端末の性能に応じて接続台数を変更してください。": [.japanese: "最大同時接続数は10台までにしていますが、使用者の端末の性能に応じて接続台数を変更してください。", .english: "最大同時接続数は10台までにしていますが、使用者の端末の性能に応じて接続台数を変更してください。"],
        "最大表示人数": [.japanese: "最大表示人数", .english: "最大表示人数"],
        "最後に、": [.japanese: "最後に、", .english: "最後に、"],
        "有効期限": [.japanese: "有効期限", .english: "有効期限"],
        "本アプリはConcept2公式のものではないので更新はできません。": [.japanese: "本アプリはConcept2公式のものではないので更新はできません。", .english: "本アプリはConcept2公式のものではないので更新はできません。"],
        "本当にありがとうございます。": [.japanese: "本当にありがとうございます。", .english: "本当にありがとうございます。"],
        "業界初('26/3/5時点)となるBLEで複数台のライブデータ取得に成功": [.japanese: "業界初('26/3/5時点)となるBLEで複数台のライブデータ取得に成功", .english: "業界初('26/3/5時点)となるBLEで複数台のライブデータ取得に成功"],
        "次に、開発案を出してくれた": [.japanese: "次に、開発案を出してくれた", .english: "次に、開発案を出してくれた"],
        "気象庁の提供する地点全てを取得可能に。": [.japanese: "気象庁の提供する地点全てを取得可能に。", .english: "気象庁の提供する地点全てを取得可能に。"],
        "潮汐データを表示したり、PM5と接続したりできる唯一の統合型アプリとなりました。": [.japanese: "潮汐データを表示したり、PM5と接続したりできる唯一の統合型アプリとなりました。", .english: "潮汐データを表示したり、PM5と接続したりできる唯一の統合型アプリとなりました。"],
        "潮汐データ取得地点を9地点から239地点へ。": [.japanese: "潮汐データ取得地点を9地点から239地点へ。", .english: "潮汐データ取得地点を9地点から239地点へ。"],
        "現在ご利用中のプランです": [.japanese: "現在ご利用中のプランです", .english: "現在ご利用中のプランです"],
        "現在のプラン": [.japanese: "現在のプラン", .english: "現在のプラン"],
        "申請の流れ": [.japanese: "申請の流れ", .english: "申請の流れ"],
        "申請完了": [.japanese: "申請完了", .english: "申請完了"],
        "申請時の表示名": [.japanese: "申請時の表示名", .english: "申請時の表示名"],
        "画面が遷移し、単一距離か単一時間ワークアウトを指定後、それぞれの目標を対応レンジ内で設定し送信します。": [.japanese: "画面が遷移し、単一距離か単一時間ワークアウトを指定後、それぞれの目標を対応レンジ内で設定し送信します。", .english: "画面が遷移し、単一距離か単一時間ワークアウトを指定後、それぞれの目標を対応レンジ内で設定し送信します。"],
        "番号": [.japanese: "番号", .english: "番号"],
        "競技力向上をサポート": [.japanese: "競技力向上をサポート", .english: "競技力向上をサポート"],
        "累積のサマリー": [.japanese: "累積のサマリー", .english: "累積のサマリー"],
        "終了時に保存/破棄を選択し、ワークアウトを終了します。": [.japanese: "終了時に保存/破棄を選択し、ワークアウトを終了します。", .english: "終了時に保存/破棄を選択し、ワークアウトを終了します。"],
        "続けることは簡単ではありません。": [.japanese: "続けることは簡単ではありません。", .english: "続けることは簡単ではありません。"],
        "編集": [.japanese: "編集", .english: "編集"],
        "練習を記録すると顧問の端末に自動配信される": [.japanese: "練習を記録すると顧問の端末に自動配信される", .english: "練習を記録すると顧問の端末に自動配信される"],
        "練習タブの使い方": [.japanese: "練習タブの使い方", .english: "練習タブの使い方"],
        "自分の中に抑えきれない何かがある時、それを思う存分さらけ出してください。（他人に迷惑をかけない範囲で）": [.japanese: "自分の中に抑えきれない何かがある時、それを思う存分さらけ出してください。（他人に迷惑をかけない範囲で）", .english: "自分の中に抑えきれない何かがある時、それを思う存分さらけ出してください。（他人に迷惑をかけない範囲で）"],
        "自動更新": [.japanese: "自動更新", .english: "自動更新"],
        "自動更新は停止されています": [.japanese: "自動更新は停止されています", .english: "自動更新は停止されています"],
        "自動更新をキャンセル": [.japanese: "自動更新をキャンセル", .english: "自動更新をキャンセル"],
        "艇種を選択": [.japanese: "艇種を選択", .english: "艇種を選択"],
        "艇速やストロークテンポを計測できるアプリを開発することを思い立ちました。": [.japanese: "艇速やストロークテンポを計測できるアプリを開発することを思い立ちました。", .english: "艇速やストロークテンポを計測できるアプリを開発することを思い立ちました。"],
        "表示個数 (列数)": [.japanese: "表示個数 (列数)", .english: "表示個数 (列数)"],
        "表示内容のカスタマイズ": [.japanese: "表示内容のカスタマイズ", .english: "表示内容のカスタマイズ"],
        "表示名を入力してください": [.japanese: "表示名を入力してください", .english: "表示名を入力してください"],
        "表示範囲（先頭からの距離）": [.japanese: "表示範囲（先頭からの距離）", .english: "表示範囲（先頭からの距離）"],
        "複数台のPM5にデータの送信ができるように": [.japanese: "複数台のPM5にデータの送信ができるように", .english: "複数台のPM5にデータの送信ができるように"],
        "見やすい配色やアイコンを選んだり、": [.japanese: "見やすい配色やアイコンを選んだり、", .english: "見やすい配色やアイコンを選んだり、"],
        "記録の取得に失敗しました": [.japanese: "記録の取得に失敗しました", .english: "記録の取得に失敗しました"],
        "記録を取得中..": [.japanese: "記録を取得中..", .english: "記録を取得中.."],
        "謝辞": [.japanese: "謝辞", .english: "謝辞"],
        "距離:": [.japanese: "距離:", .english: "距離:"],
        "送信するとともにアプリ内の数値がPM5の画面と合致するので、任意のタイミングでワークアウト開始します。": [.japanese: "送信するとともにアプリ内の数値がPM5の画面と合致するので、任意のタイミングでワークアウト開始します。", .english: "送信するとともにアプリ内の数値がPM5の画面と合致するので、任意のタイミングでワークアウト開始します。"],
        "送信後、ダッシュボード画面に自動で遷移し全ての接続状況やワークアウト状況が見られます。": [.japanese: "送信後、ダッシュボード画面に自動で遷移し全ての接続状況やワークアウト状況が見られます。", .english: "送信後、ダッシュボード画面に自動で遷移し全ての接続状況やワークアウト状況が見られます。"],
        "閉じる": [.japanese: "閉じる", .english: "閉じる"],
        "開発の手伝いをしていただけたのです。": [.japanese: "開発の手伝いをしていただけたのです。", .english: "開発の手伝いをしていただけたのです。"],
        "開発者から": [.japanese: "開発者から", .english: "開発者から"],
        "開発者からのメッセージ": [.japanese: "開発者からのメッセージ", .english: "開発者からのメッセージ"],
        "顧問からチーム招待コードをもらう": [.japanese: "顧問からチーム招待コードをもらう", .english: "顧問からチーム招待コードをもらう"],
        "顧問から共有された8文字のチーム招待コード": [.japanese: "顧問から共有された8文字のチーム招待コード", .english: "顧問から共有された8文字のチーム招待コード"],
        "顧問から共有された招待コードを入力してチームに参加します。": [.japanese: "顧問から共有された招待コードを入力してチームに参加します。", .english: "顧問から共有された招待コードを入力してチームに参加します。"],
        "顧問が承認するとチームに追加される": [.japanese: "顧問が承認するとチームに追加される", .english: "顧問が承認するとチームに追加される"],
        "顧問の先生": [.japanese: "顧問の先生", .english: "顧問の先生"],
        "顧問やチームリーダーから発行された\nチーム招待コードを入力してください": [.japanese: "顧問やチームリーダーから発行された\nチーム招待コードを入力してください", .english: "顧問やチームリーダーから発行された\nチーム招待コードを入力してください"],
    ]

    
    
    /// Get localized string
    func string(_ key: String) -> String {
        return translations[key]?[language] ?? key
    }
    
    func setLanguage(_ displayLanguage: AppLanguage) {
        self.language = displayLanguage
    }
}

extension String {
    var localized: String {
        return LocalizationManager.shared.string(self)
    }
}
